### ISSUE TITLE
Unittest framework

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit#1]
Which unittest framework do we want to use? [Pytest](https://docs.pytest.org/en/stable/) seems popular - anything newer/better we should be aware of/use?

**Comment by tomwhite** [comment]
+1 to pytest - it's widely used and pretty powerful.

**Comment by hammer** [comment]
It seems that pytest is the default selection for Python projects right now. I will note that it has an extensive plugin ecosystem, so perhaps a more contentious discussion would be which plugins to use?

I listened to a [podcast](https://talkpython.fm/episodes/show/267/15-amazing-pytest-plugins) recently that coveraged 15 different plugins, for example.

**Comment by tomwhite** [comment]
Closing this since we are using pytest now.
