### ISSUE TITLE
Consistent naming for IO functions

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#1004]
There are a number of inconsistencies and gaps in our naming:

| Format | Format -> Zarr | Zarr -> Format | Format -> Dataset | Dataset -> Format |
|--------|----------------|----------------|--------------------|-------------------|
| BGEN | `bgen_to_zarr` | | `read_bgen` | |
| PLINK | `plink_to_zarr` [3] | `zarr_to_plink` | `read_plink` | `write_plink` (in #1003) |
| VCF | `vcf_to_zarr` | `zarr_to_vcf` | `read_vcf` [2] | `write_vcf` [1] |

I propose
~~1. Rename `dataset_to_vcf` to `write_vcf` before it is released. #1005~~
~~2. Add `read_vcf`, which will also address #909. #1052~~
~~3. Add `plink_to_zarr` (#309) and `zarr_to_plink` since they are simple to implement using `read_plink` and `write_plink` #1047~~

We don't current plan to support writing BGEN, so there is no `zarr_to_bgen` or `write_bgen`.

**Comment by jeromekelleher** [comment]
Looks great, very nice.

**Comment by tomwhite** [comment]
Closing this as the names are now consistent
