### ISSUE TITLE
When converting large VCFs ~50% of wall clock time is spent deleting temporary files

### ISSUE THREAD

**Issue by benjeffery** [pystatgen/sgkit#1036]
After the `concat_zarrs` step the temporary zarr files have to be deleted. As the VCF to convert gets larger the fraction of time taken by this step of the process rises - becoming more than half the time above a ~5GB compressed VCF, at least on the `NFS` system I'm using. This step should also use dask to parallelize the deletion of the files.

**Comment by hammer** [comment]
Can we shell out and use `find ... -delete` on Linux?

**Comment by tomwhite** [comment]
Thanks for the report - it's interesting that it takes so long to delete these files as a proportion of the total time at these scales. (I seem to remember that we had to parallelize file deletion in Hadoop jobs for the same reason...)

The file deletion is occurring in this line: https://github.com/pystatgen/sgkit/blob/b6d4eac9f55aa8bc7b8e74b516aa0e04beae1090/sgkit/io/vcf/utils.py#L171

One option would be to use Dask Delayed to delete subdirectories in parallel - this might need a bit of care to get the granularity right.

Another option would be for the code to leave the temporary files in place, then the user can delete them "out of band" using external tools. These might be Unix tools as @hammer suggested, or other tools when using cloud storage. Would this work for you? (This would be simpler to implement.)

One thing I have used successfully on another project when using cloud storage is to write intermediate temporary data to a separate bucket, and set an expiration policy on that bucket of "delete after 24 hours". Then you can just forget about it. See https://lepczynski.it/en/aws_en/automatically-delete-old-files-from-aws-s3/ and https://cloud.google.com/storage/docs/managing-lifecycles

**Comment by benjeffery** [comment]
The issue here seems to be NFS latency, I assume the total time taken is roughly `latency * num_files`. A quick test shows that `rm` takes a similar amount of time if I do that manually outside the python process. On this project, I don't have the option of setting a delete policy, but that is a good idea for cloud-based projects.

I think a flag to retain the temp files would be simplest, I can leave `find ... -delete` going after it is all done. I'm happy to implement this.

**Comment by tomwhite** [comment]
> I think a flag to retain the temp files would be simplest, I can leave `find ... -delete` going after it is all done. I'm happy to implement this.

Great - sounds good.
