### ISSUE TITLE
Method to convert genotypes to index

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#1048]
This operation collapses `call_genotype` across the ploidy dimension to give an index as described here: https://github.com/pystatgen/sgkit/discussions/1040#discussioncomment-5184713

**Comment by timothymillar** [comment]
Feel free to assign this to me

**Comment by timothymillar** [comment]
@tomwhite I have opened a PR for this, but I wonder if we should also add the inverse method `convert_index_to_genotype_call`?

**Comment by tomwhite** [comment]
Thanks for implementing this @timothymillar. 

> @tomwhite I have opened a PR for this, but I wonder if we should also add the inverse method `convert_index_to_genotype_call`?

Maybe as a separate issue/PR?
