### ISSUE TITLE
Add zarr to setup.cfg

### ISSUE THREAD

**Issue by eric-czech** [pystatgen/sgkit#105]
In https://github.com/pystatgen/sgkit/pull/40, zarr should have been added to [setup.cfg#L27](https://github.com/pystatgen/sgkit/blob/dce23d09dcac61d6cd5f7b71fa59f65eb4ff3176/setup.cfg#L27) as well as 
[requirements.txt#L5](https://github.com/pystatgen/sgkit/blob/dce23d09dcac61d6cd5f7b71fa59f65eb4ff3176/requirements.txt#L5).  This seems to be breaking the build in the IO repos.

**Comment by ravwojdyla** [comment]
Related #65
