### ISSUE TITLE
Investigate mergify

### ISSUE THREAD

**Issue by ravwojdyla** [pystatgen/sgkit#107]
I will close this issue, and create a separate one for `mergify`.

_Originally posted by @ravwojdyla in https://github.com/pystatgen/sgkit/issues/26#issuecomment-673381620_

Related: https://github.com/pystatgen/sgkit/issues/26#issuecomment-655656832

**Comment by ravwojdyla** [comment]
FYI, I have done a quick review of mergify features, we could automate a lot of PR related actions, see full [doc](https://doc.mergify.io/actions.html). Mergify itself is now enabled for pystatgen org (thanks @hammer). Since this is just the beginning of the project, I wonder if it's better to hold off automatic merge for a bit until we crystallise the patterns/groups/reviewers etc around PRs, for example: 
 * how many reviewers do we requires and from which groups
 * do we reset reviews on PR updates
 * do we bypass reviews in certain cases (small PRs, ex: new dependency)

We could try to have this discussion right now(?), alternatively we could give ourselves some more time to naturally build up those patterns and then codify them via mergify.

In the meantime I will submit a minimal mergify config to:
 * ping authors on conflicts
 * delete merged branches

Btw, a simple rebase config for use could look like [this](https://github.com/Mergifyio/mergify-engine/blob/master/.mergify.yml#L1-L17).

How does that sound? (@tomwhite @eric-czech @jeromekelleher)

**Comment by eric-czech** [comment]
Sounds good to me.  Codifying the review process as part of the minimal config now sounds good too, though I would vote that we start start conservatively with:

- Require 1 reviewer (from anywhere)
- Don't reset reviews on PR updates
- No bypass on reviews

That's been the process so far in my head anyhow.

**Comment by ravwojdyla** [comment]
@eric-czech thanks. I added a simple mergify script that has a auto merge op-in option by labelling PR `auto-merge`, see in #122

**Comment by jeromekelleher** [comment]
The way we've done it in [tskit](https://github.com/tskit-dev/tskit/blob/master/.mergify.yml) is to have an AUTOMERGE-REQUESTED label, which people with sufficient privileges can add. This will only work if certain conditions are met (>= approvals, tests pass, etc). This is working really well, as it gives a bit of flexibilty where things aren't automatically merged after one review goes in (suppose there's a big controversial PR - we might want 3 approvals before it's mergable), and for less controversial things there's minimal bureaucracy (X makes the PR, Y approves it and marks it as AUTOMERGE-REQUESTED, it gets rebased and merged automatically, done).

I'd suggest this config as a starting point as we know it works, unless there's compelling reasons not to.

**Comment by ravwojdyla** [comment]
@jeromekelleher yea, that is already in place in #122 (and yes, I stole it from tskit).

**Comment by jeromekelleher** [comment]
Apologies @ravwojdyla, my bad - I didn't see the automerge label, I thought it was just merging immediately after one approval. Great, let's try it out!

**Comment by tomwhite** [comment]
Sounds good to me. What do we have to do to use it?

**Comment by ravwojdyla** [comment]
@tomwhite label your PR with `auto-merge`, and once you get at least one +1 and a clean build it will get merged.
