### ISSUE TITLE
Pedigree visualisation

### ISSUE THREAD

**Issue by timothymillar** [pystatgen/sgkit#1097]
Add a simple method for pedigree visualization using graphviz.

I've been thinking about documentation/examples for working with pedigree data and one of the current limitations is visualization. I'm not intending on "publication ready" visuals, but rather a straightforward method for sense-checking data (similar to `display_genotypes`).

The simplest option is to use graphviz, which is already an optional dependency for visualizing dask graphs (it could still be optional). This won't be very performant for larger pedigrees, but it should be good enough for common use-cases. We can allow some customization by passing through arrays to use as node and edge attributes (broadcast to the appropriate size).

Here's some rough examples using the mixed-ploidy pedigree published by Hamilton and Kerr (with simulated genotypes):

Default to using sample_id as labels:
```python
visualize_pedigree(ds)
```
![HK_pedigree_1 gv](https://github.com/pystatgen/sgkit/assets/14065102/3b36d529-4b43-4077-b7db-89eb2fa34f53)

Use genotype strings as labels:
```python
labels = label=genotype_as_bytes(ds.call_genotype.values[0], phased=False).astype('U')
visualize_pedigree(
    ds,
    node_attrs=dict(label=labels)
)
```
![HK_pedigree_2 gv](https://github.com/pystatgen/sgkit/assets/14065102/be32a0df-bace-44a7-bac1-4f53c9601662)

Indicating gametic ploidy (tau) with edge style:
```python
edges = xr.where(
    ds.stat_Hamilton_Kerr_tau == 2,
    "black:black",
    "black",
)
visualize_pedigree(
    ds,
    node_attrs=dict(label=labels),
    edge_attrs=dict(color=edges),  # broadcast to (samples * parents)
)
````
![HK_pedigree_3 gv](https://github.com/pystatgen/sgkit/assets/14065102/57d144f9-18f6-482a-b8f2-99ddefd39973)

**Comment by timothymillar** [comment]
Related to #1012

**Comment by benjeffery** [comment]
Nice!

**Comment by jeromekelleher** [comment]
We used networkx to do this in the [msprime docs](https://tskit.dev/msprime/docs/latest/pedigrees.html#visualising-pedigrees). Gives reasonably good results, for not much code. See this example: https://tskit.dev/msprime/docs/latest/ancestry.html#pedigrees-and-demography

Using a pre-existing dependency is a good call though, we don't want to pull in more stuff just for this.
