### ISSUE TITLE
Guidelines for method implementations

### ISSUE THREAD

**Issue by eric-czech** [pystatgen/sgkit#11]
How should we define methods that operate on datasets like those in https://github.com/pystatgen/sgkit/pull/10?

More specifically, I'm wondering how we want to invoke them given that there will be a need for multiple implementations, e.g.:
  - GPU vs CPU 
  - sparse vs dense
  - multiple algorithms with the same interface, such as:
    - sequential vs iterative versions of maximal independent set solvers
    - tall-skinny vs fully chunked LD calculations
  - chunked vs in-memory 
     - presumably we can ignore this and just write chunked implementations with single chunks as a degenerate case

The solution for this would be similar to what @alimanfoo is asking about in https://github.com/pystatgen/sgkit/issues/3.  I don't think it will be too difficult to make some of these "backend" choices transparent in the future (based on data content + installed software), but perhaps we should ignore that for now.

Do you have any thoughts on how we should manage this @tomwhite?  Let me know if any more examples would be helpful.

**Comment by hammer** [comment]
Some related [discussion](https://discourse.smadstatgen.org/t/development-and-dispatch-for-genetics-methods-over-pydata-libraries/46) on Discourse.

**Comment by tomwhite** [comment]
I wonder if there are two concepts here: "algorithm" and "backend"? An algorithm would be tied to the method (e.g. "sequential" for a maximal independent set method), whereas a backend would just be a linear algebra implementation like "numpy", "dask", or "dask+cuda" that would work for all methods.

Most methods probably have a single algorithm, so they don't need to take an "algorithm" argument. Backends are normally selected by the type of the input array, but I think there is a case for offering the user more control. For example, the input may be a regular NumPy array, but the user knows that running on a GPU is good choice for a particular method, so they want to say `backend="cupy"` in this case, and have the array converted for them.

Dispatching on type is well catered for in PyData. We could use NumPy's `__array_function__` (NEP 18), multiple-dispatch, unumpy, or the forthcoming [NEP-37](https://numpy.org/neps/nep-0037-array-module.html). Of these, only unumpy seems to allow a way of explicitly selecting a backend by coercing the type. But we could explicitly do the conversion in each method function using helper methods.

None of these allow selecting by data size, which is something we will want in the future. A new backend keyword could be used to select this mode, or possibly another optional argument. It could also be built a part of the "macro-like" functions, which comprise multiple stages of the workflow, as discussed here: https://discourse.smadstatgen.org/t/development-and-dispatch-for-genetics-methods-over-pydata-libraries/46/4.

For now, I think we should have an API that allows the backend to be specified as an optional function argument. The actual dispatching machinery should remain an implementation detail. Later it should be possible to set the backend via a context manager, or via config. (See the last section of this notebook by @eric-czech https://nbviewer.jupyter.org/github/related-sciences/gwas-analysis/blob/master/notebooks/platform/xarray/dispatching.ipynb)

**Comment by tomwhite** [comment]
On the two-level API (https://discourse.smadstatgen.org/t/development-and-dispatch-for-genetics-methods-over-pydata-libraries/46/3), is it worth having two levels, but only exposing the xarray (higher-level) API to users for the time being? Separating them out may be useful for unit testing, but I'm not sure we need to expose the internal "raw" array API (yet).

**Comment by alimanfoo** [comment]
> On the two-level API (https://discourse.smadstatgen.org/t/development-and-dispatch-for-genetics-methods-over-pydata-libraries/46/3), is it worth having two levels, but only exposing the xarray (higher-level) API to users for the time being? Separating them out may be useful for unit testing, but I'm not sure we need to expose the internal "raw" array API (yet).

FWIW that sounds good to me. I.e., the higher-level API is the user API, and the lower-level API is the developer API.

**Comment by alimanfoo** [comment]
+1 for separating algorithm and backend concepts.

**Comment by eric-czech** [comment]
Thanks for looking into it @tomwhite!  An assumption I've been making so far in starting to write some code is that the "dask+cupy", "dask+numpy", "dask+sparse" backends will be important but implementations without dask aren't.  How do you feel about that @alimanfoo?  I don't see why every method would need to work that way but I had put a higher priority on dask-free implementations in my prototyping (largely in reimagining the skallel v2 examples on Xarray) even though we wouldn't likely use them.  Do you foresee dask introducing substantial issues/inefficiencies when operating on arrays that are small enough to fit into memory in the first place?

> For now, I think we should have an API that allows the backend to be specified as an optional function argument

👍 

> Separating them out may be useful for unit testing, but I'm not sure we need to expose the internal "raw" array API (yet).

Sounds good.

**Comment by alimanfoo** [comment]
> An assumption I've been making so far in starting to write some code is that the "dask+cupy", "dask+numpy", "dask+sparse" backends will be important but implementations without dask aren't. How do you feel about that @alimanfoo? I don't see why every method would need to work that way but I had put a higher priority on dask-free implementations in my prototyping (largely in reimagining the skallel v2 examples on Xarray) even though we wouldn't likely use them.

FWIW I think I'd always aim to include a plain "numpy" (i.e., CPU in-core) implementation, then aim to add at least a "dask+numpy" implementation for any function likely to operate on larger inputs and/or generate large outputs. 

The benefits of the plain numpy implementation are that the algorithm is simpler (no need to consider parallelism or chunking) and so it's easier to get right and easier to debug when you get it wrong. I.e., I'd use the numpy backend as the reference implementation. Also there's a lower bar to contribution, i.e., someone can contribute a new function with a plain numpy implementation, and then later someone else could work on a dask+numpy implementation to scale it up if needed.

There are also plenty of useful functions that might never need a dask backend.

**Comment by hammer** [comment]
Do we need more discussion on this issue, or should we just close this out and address dispatch questions as they come up during the implementation of specific core operations?

**Comment by eric-czech** [comment]
The latter I think -- I'll close it out since my questions were all touched on.
