### ISSUE TITLE
read_plink failing with 0.7.0 release

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#1149]
I've tried `read_plink` on 2 different PLINK file families and gotten the same error both times (pasting from VS Code with nice formatting):

<img width="788" alt="Screenshot 2023-11-28 at 11 02 38 PM" src="https://github.com/pystatgen/sgkit/assets/15233/5c548a82-3bf7-43d8-933a-3172e11939e3">

This looks to be https://github.com/pystatgen/sgkit/issues/1085. I will try installing from source and see if the error clears up.

**Comment by hammer** [comment]
I have confirmed that building from source restores `read_plink` functionality. Should we cut a 0.7.1 release so that a release version can read PLINK files?

**Comment by jeromekelleher** [comment]
Yes, we probably should. Should we make a milestone and triage stuff we want to get into 0.7.1?

**Comment by PxxxxN** [comment]
> I have confirmed that building from source restores `read_plink` functionality. Should we cut a 0.7.1 release so that a release version can read PLINK files?
Hello, could you please tell me more about your solution process? I also encountered the same problem:)

**Comment by hammer** [comment]
@PxxxxN one solution would be to install `sgkit` with `pip` from GitHub. Here's a useful guide: https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository.

The precise syntax will depend on your python installation, but it will probably look something like:

```
python -m pip install 'sgkit @ git+https://github.com/pystatgen/sgkit.git#sgkit[plink]'
```

**Comment by jeromekelleher** [comment]
Closing this as the code has already been fixed.
