### ISSUE TITLE
read_plink scalability

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#1152]
Can we get the scalability fixes from https://github.com/pystatgen/sgkit-publication/issues/35 into `read_plink` too? cc @benjeffery

**Comment by benjeffery** [comment]
From what I can tell the plink parser loads the data into cluster memory, instead of writing parts to disk as the VCF parser does. Therefore this issue doesn't apply - your workers have to last until you save the dataset. Happy to re-open if I've got the wrong end of the stick.

**Comment by hammer** [comment]
Oh boy, sounds like I've got some workers falling over due to memory issues in my future...

**Comment by benjeffery** [comment]
I'm happy to help out here, have quite a few dask battle scars at this point!

**Comment by tomwhite** [comment]
A quick note following yesterday's discussion in the meeting: the plink reader in sgkit will only read the portion of the BED file for the Zarr chunk being written (see https://github.com/pystatgen/sgkit/blob/main/sgkit/io/plink/plink_reader.py#L83). In other words, it should already handle file splitting and scaling out to large files.
