### ISSUE TITLE
Add packaging for the project

### ISSUE THREAD

**Issue by eric-czech** [pystatgen/sgkit#12]
The immediate need I have for being able to install the project is in CI builds for a repo with a dependency on this one (sgkit-plink).

Is there any reason not to use setuptools-scm, e.g. as in xarray (ping @tomwhite)?

**Comment by jeromekelleher** [comment]
I use ``setuptools-scm``, and it works well most of the time. I couldn't get it work for [tskit](https://github.com/tskit-dev/tskit), but it's a complicated multi-language repo, and we're not dealing with that type of complexity here (right?).

**Comment by tomwhite** [comment]
I haven't used it but setuptools-scm looks like a good option.

**Comment by tomwhite** [comment]
Can this be closed now @eric-czech?

**Comment by eric-czech** [comment]
Yep!  Closing now.
