### ISSUE TITLE
partition_into_regions returns empty region for all contigs in header

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit#1200]
This [line](https://github.com/pystatgen/sgkit/blob/d32b8714e026b5e0ab49812a87174edbd829b26a/sgkit/io/vcf/vcf_partition.py#L190) adds an empty region for every contig that's in the VCFs header in ``partition_into_regions``. However, it's common for VCFs to have contigs declared in the header that are not in the file at all. For example, recent 1000 Genomes data declares all contigs in all VCF files (there are thousands). This generates a lot of noise in the returned region strings.

What was the rationale for returning the empty regions @tomwhite?

**Comment by jeromekelleher** [comment]
Possible explanation for  #1169 ?

**Comment by tomwhite** [comment]
> What was the rationale for returning the empty regions @tomwhite?

Not sure. It seems it can be removed though.

**Comment by jeromekelleher** [comment]
Digging deeper, it's not quite as simple as this. Turn out that all three of CSI indexed BCF, CSI indexed VCF and tabix indexed VCF need to be treated slightly differently in these  cases in which there are multiple contigs defined in the header :vomiting_face:

**Comment by jeromekelleher** [comment]
Closing in favour of #1201 (more precisely specified)
