### ISSUE TITLE
Improve contributing docs

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#125]
A few things missing:
- [x] information about Mergify #107 
- [x] file an issue before submitting a PR and be sure to mention the issue in the PR comments
- [ ] clarify docstring style https://github.com/pystatgen/sgkit/pull/114#issuecomment-676584075

**Comment by hammer** [comment]
@jerowe @daletovar @timothymillar would love your input on what we need to add/remove/change in our contributing docs.

**Comment by tomwhite** [comment]
> file an issue before submitting a PR and be sure to mention the issue in the PR comments

On https://pystatgen.github.io/sgkit/contributing.html#issues it already says,

> Before starting work, make sure there is an issue covering the feature or bug you plan to produce a pull request for.

But it should be changed to say to mention the issue in the PR comments.

**Comment by hammer** [comment]
@jeromekelleher mentioned in the [last developer call](https://discourse.pystatgen.org/t/20200827-developer-call-notes/91) that he had a [guide](https://stdpopsim.readthedocs.io/en/latest/development.html#github-workflow) from another project that could be useful to link from our documentation.

There's also been some discussion in #129 and #140 on the use of branches in developer forks and how to keep those branches up to date. Do we need to add some text to our contributing docs to reflect the consensus from those issues?

**Comment by hammer** [comment]
Also I believe https://github.com/pystatgen/sgkit/issues/216 addresses the docstring style task above.

**Comment by hammer** [comment]
@tomwhite do we need to augment the contributing docs to ensure we don't miss functions when building the Sphinx docs as in https://github.com/pystatgen/sgkit/issues/212?

**Comment by aktech** [comment]
I see #212 is closed, but I still don't see `stats` and `io` modules docs, is that intentional?

> do we need to augment the contributing docs to ensure we don't miss functions when building the Sphinx docs as in #212?

The instructions for the same does seems to be fixing here: https://pystatgen.github.io/sgkit/contributing.html#docstrings

> Also I believe #216 addresses the docstring style task above.

I have made a comment here on my understanding of the same: https://github.com/pystatgen/sgkit/issues/216#issuecomment-688964428

Let me know, if these makes sense, I will open a PR for the same.

**Comment by aktech** [comment]
@tomwhite @hammer Can this be closed now? as #261 is merged
