### ISSUE TITLE
Configure mergify to rebase on branch update and merge on "merge"

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit#130]
Currently it looks like mergify is set up to merge to bring branches up to date, and rebase to merge. This leads to confusing history graphs:

![Screenshot from 2020-08-20 17-35-11](https://user-images.githubusercontent.com/2664569/90800731-f2275c80-e30c-11ea-842d-1ecded742299.png)

On the other hand, if we configure mergify to rebase to branch update and merge to merge, we get a nice linear history with a clear indication of the composition of the PRs. 

![Screenshot from 2020-08-20 17-33-28](https://user-images.githubusercontent.com/2664569/90800736-f489b680-e30c-11ea-8cd2-3bd32ebe6008.png)

**Comment by jeromekelleher** [comment]
Well, none of the drawbacks they mention matter much to us except the last one (the person credited with rebasing is arbitrary), I think, and we can work around that by having a merge-bot account.

I honestly don't see the advantage of throwing away the PR history (which is the only real difference between the scemes), but if no-one else complains I'll drop it.

**Comment by ravwojdyla** [comment]
> Due to the change of all commits SHA-1 of the pull request, your contributor will need to force-push its own branch if they add new commits.

Is relatively significant too.

**Comment by jeromekelleher** [comment]
Closing this after agreement during weekly meeting.
