### ISSUE TITLE
Simulated datasets don't serialize

### ISSUE THREAD

**Issue by eric-czech** [pystatgen/sgkit#139]
You can't currently save a dataset from `sgkit.testing.simulate_genotype_call_dataset` because the attributes contain numpy scalars which don't serialize as JSON when calling `ds.to_zarr`.  The simplest fix would be to have the function convert contig names to Python ints/string in https://github.com/pystatgen/sgkit/blob/master/sgkit/testing.py#L56.  A better fix would be to have `create_genotype_call_dataset` guard against this.

**Comment by hammer** [comment]
Should this be closed or should it remain open until the "better fix" is implemented?

**Comment by eric-czech** [comment]
I would say that my "better fix" isn't that important now that https://github.com/pystatgen/sgkit/issues/252 is on the way.  That, the to_zarr/from_zarr test in https://github.com/pystatgen/sgkit/pull/331, and the tests necessary for https://github.com/pystatgen/sgkit/issues/298 are all enough IMO to say that it should become very unlikely for a user to run into the issue I had in the future.
