### ISSUE TITLE
Questions on best practices

### ISSUE THREAD

**Issue by eric-czech** [pystatgen/sgkit#15]
In beginning to write methods, a number of questions came to mind:

- How hesitant should we be to pollute our dev/build environment with dependencies needed to validate methods?  `statsmodels` is a relatively lightweight example where I'd like to be able to verify regression statistics with it, but it's not particularly well maintained and might introduce some issues down the road with relying on older versions of scipy/numpy/etc.  Hail and scikit-allele are other examples where I would like to demonstrate equivalency for certain things and while showing this is really only necessary at first, it would be nice if there was a way to make that kind of verification recurrent.  A few possible approaches could be:
  - Make any validation relying on packages that do something at a higher level than array ops (e.g. anything w/ statistics or genetics) part of integration (or "validation") test process with separate environments
  - Export data from software like this and use only the data in unit tests.  This is what I usually do but typically without much documentation/reproducibility -- I'd rather have a good place to document/share that process. Maybe an `sgkit-validation` repo would be a good place to organize/document these scripts with messy environments?
  - Do nothing.  I haven't seen this done much in other projects so perhaps we don't make it a priority.  The stringency of our tests will likely slip but it may be worth avoiding all the extra complexity.
- Should we add readthedocs integration now?  I'd like to not have to reformat all my docstrings later and it would be nice to know what conventions we want to follow.
- Is there a preferred way to organize publication references within a scientific codebase?  I started adding Chicago style citations in a docstring "References" block, but I'm not sure what the best practice for this is.  Scikit-learn is probably a good model to follow, though I don't know how they organize references (e.g. [orthogonal-matching-pursuit-omp](https://scikit-learn.org/stable/modules/linear_model.html#orthogonal-matching-pursuit-omp)).  Seems to be a combination of "Notes" in docstrings and separate references sections in .rst docs
- Are we taking a hard line on single vs double string quoting?  I prefer single quotes, but I'm happy to try to remember to stick with one or the other.

**Comment by eric-czech** [comment]
As for point #1 above, it could also make sense to piggy-back off of @alimanfoo's suggestion in https://github.com/pystatgen/sgkit/pull/9 for handling public datasets as a way to manage validation data too.  An intake catalog seems extreme for this but colocating the environments, scripts, and documentation in the same place appears reasonable.

**Comment by tomwhite** [comment]
> How hesitant should we be to pollute our dev/build environment with dependencies needed to validate methods?

I don't think we should do nothing. Validating methods is an important part of quality testing, and serves as a regression test. Either (or a mixture of both) of the suggested approaches would work, and I don't see why the code and scripts couldn't live in a test area of this repo.

> Should we add readthedocs integration now?

+1 to generating docs now.

> Are we taking a hard line on single vs double string quoting?

Black will convert them all to double quotes, so you don't need to worry about it.

**Comment by jeromekelleher** [comment]
The unit-vs-validation testing distinction is tricky. How do we do unit tests if we can't check the answer? But, on the other hand, once you start checking statistical outputs in the unit tests, it's very difficult to avoid the unit test suite becoming slow. Maybe the thing to do is keep the unit tests very, very simple, and keep all checking of statistical correctness in the validation tests? This would make it *much* easier for regressions to slip through, though. 

I think there must be some checking for statistical correctness in the unit tests, and having dependencies on a small number of external packages is fine for this. For population genetics methods, I think we can use tskit, scikit-allel and maybe [pylibseq](https://pypi.org/project/pylibseq/0.1.5/) to validate against. Tskit and scikit-allel are straightforward dependencies. We can generate test data for popgen stuff using msprime, which is also a well behaved dependency.

**Comment by hammer** [comment]
> Should we add readthedocs integration now?

I filed #19 for this discussion.

**Comment by hammer** [comment]
>Is there a preferred way to organize publication references within a scientific codebase?

Paging @dhimmel

**Comment by dhimmel** [comment]
> Is there a preferred way to organize publication references within a scientific codebase?

I don't think there are well adopted standards here. IMO a title and URL are sufficient. For example, if your docstrings support markdown you could do:

```markdown
- [SAGA: A Fast Incremental Gradient Method With Support for Non-Strongly Convex Composite Objectives](https://arxiv.org/abs/1407.0202)
```

Most things looking through the source code or auto-generated docs are either humans (which can look at the title and follow the link) or search engines (which care about the link). Also you'll likely have many references that aren't to traditional publications, like GitHub Issues or StackExchange comments. Styles like Chicago are a bit outdated when it comes to representing online forum posts.

For actual references in a publication, I like Manubot's reference style ([example](https://manubot.github.io/rootstock/#references)), but I'm partial since I helped design it. But in code, I generally just do title and URL, possibly with first author last name and year of publication if those details are helpful.

**Comment by eric-czech** [comment]
Closing this since everything was moved out or addressed.  

I'm still not sure where to draw the line with unit testing and validation testing, but I'll keep more extensive validation code/environments ready to go (but separate) until it's clear what to do with it.
