### ISSUE TITLE
Documentation process and tools

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#19]
The Hitchhiker's Guide to Python [suggests](https://docs.python-guide.org/writing/documentation/) [Sphinx](https://www.sphinx-doc.org/en/master/) to author documentation and [Read the Docs](https://docs.readthedocs.io/en/stable/) to host it.

There have been some new developments in this domain recently, so let's evaluate our options before selecting a process and tools.

**Comment by hammer** [comment]
Sphinx appears to use [reStructuredText](https://docutils.sourceforge.io/rst.html) as its markup language and [Docutils](https://docutils.sourceforge.io/) to parse and generate documents.

I found [Who needs pandoc when you have Sphinx?](https://speakerdeck.com/stephenfin/who-needs-pandoc-when-you-have-sphinx?slide=12) to be a useful description of what Sphinx adds to Docutils.

**Comment by hammer** [comment]
Another approach is to use [MkDocs](https://www.mkdocs.org/) to author and generate documents and then GitHub pages or Google Cloud to host the docs.

https://github.com/scifabric/docs.pybossa.com is an example of this approach.

**Comment by hammer** [comment]
It appears that offline documentation browsers like [Zeal](https://zealdocs.org/), [Dash](https://kapeli.com/dash), and [DevDocs](https://devdocs.io/) are popular. I don't use any of these, but if it's not too hard, we should ensure our docs can be imported into those tools.

**Comment by hammer** [comment]
[NumPy’s Documentation](https://numpy.org/doc/stable/docs/index.html) has information on how NumPy does documentation, including [numpydoc](https://github.com/numpy/numpydoc/), their Sphinx extensions.

**Comment by hammer** [comment]
Some other options
- [Docusaurus](https://docusaurus.io/) from Facebook seems to have a lot of flexibility for generating nice documentation sites. I'm not sure we have enough frontend development skills to make this tool a reasonable choice.
- [GitBook](https://www.gitbook.com/#ProductsDocs) (disclosure: I'm an investor) is another option if we want to make a fancy site.

**Comment by jeromekelleher** [comment]
Sphinx is great, I think we'd want some compelling motivation to use anything else tbh. I don't have any real opinions in terms of themes and hosting.

If it's at all feasible, I'd suggest using Markdown rather than RST though. Markdown is just so much more intuitive, and many more people know it. It's a real barrier to contributors asking them to learn RST when doing docs. But I haven't investigated how good Markdown support in sphinx is, so it might be a non-starter.

**Comment by hammer** [comment]
Hail recently [added](https://github.com/hail-is/hail/pull/8955/commits) documentation search using Algolia's [DocSearch](https://docsearch.algolia.com/).

**Comment by hammer** [comment]
>I'd suggest using Markdown rather than RST

While that was my strong bias headed into this survey, I was surprised to find that most PyData ecosystem projects still use reStructuredText, so I think it may be worth asking some developers on those more mature projects why they haven't switched.

**Comment by hammer** [comment]
I suppose https://github.com/pystatgen/sgkit/pull/9 is related to this discussion.

**Comment by jeromekelleher** [comment]
> I think it may be worth asking some developers on those more mature projects why they haven't switched.

I'd bet on one word: inertia. It's a whole pile of work to switch - I know that's why I haven't done it.

**Comment by alimanfoo** [comment]
FWIW I do prefer markdown over rst and did recently look at [support for markdown in sphinx](https://www.sphinx-doc.org/en/master/usage/markdown.html). Bottom line I think you can use markdown, but it wasn't obvious how to use many of the sphinx features within it, like all the [sphinx directives](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html). There's a [relevant SO post here](https://stackoverflow.com/questions/2471804/using-sphinx-with-markdown-instead-of-rst).

**Comment by hammer** [comment]
Ah we were looking separately at [MyST](https://myst-parser.readthedocs.io/en/latest/) as a format for Jupyter notebook code reviews. That may be our best bet to get Markdown syntax and Sphinx directives.

**Comment by alimanfoo** [comment]
MyST looks good.

Btw for jupyter notebook code reviews we use [reviewnb](https://www.reviewnb.com/).

**Comment by hammer** [comment]
> for jupyter notebook code reviews we use [reviewnb](https://www.reviewnb.com/).

We've hit some deficiencies with this product, unfortunately, so are searching for alternatives at the moment.

**Comment by alimanfoo** [comment]
> > for jupyter notebook code reviews we use [reviewnb](https://www.reviewnb.com/).
> 
> We've hit some deficiencies with this product, unfortunately, so are searching for alternatives at the moment.

Ah OK, would be interested to know what you missed and what alternatives you find. Pretty key tool in our analysis work, has been fine so far but have missed the ability to make line comments.

**Comment by tomwhite** [comment]
I'd rather go with something that is proven to work well, even if it's a bit harder to get up to speed on (RST + Sphinx) than newer things that have gaps in areas we don't know if we need yet.

**Comment by hammer** [comment]
@tomwhite as [noted](https://twitter.com/asmeurer/status/1272951514890301440) by Aaron Meurer on Twitter, once nice thing about MyST is that we don't need to commit entirely to it:

> With myst you can write markdown in .md files and still use restructured text in .rst files. And cross references work between them

I also did not realize that MyST was only [publicly announced](https://twitter.com/choldgraf/status/1272633413132943360) on June 15! The comments on that tweet are useful. In particular, one user notes that MyST does not yet work for docstrings, and points to the [napoleon](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/) docstring preprocessor that I had not heard about. https://github.com/executablebooks/MyST-Parser/issues/164 has been filed to close the docstring loophole for MyST.

It's also interesting to look at issues and PRs from projects that have moved to MyST already, e.g. https://github.com/poliastro/poliastro/issues/977 and https://github.com/asmeurer/brown-water-python/pull/2.

While I'm generally in the "use boring technologies" camp, especially for things like documentation, I am also in the "don't make me learn another domain-specific language" camp, and would love to be able to write Markdown.

Does it make sense to try to use MyST in one place first, perhaps in one of our IO repos?

**Comment by tomwhite** [comment]
> Does it make sense to try to use MyST in one place first, perhaps in one of our IO repos?

I was hoping we could avoid having separate documentation for each repo, and just have a single set of docs in one repo, so we can avoid the problem of knitting it all together. The IO docs will be fairly small, so putting them in the main repo shouldn't be too much of a stretch.

**Comment by hammer** [comment]
> The IO docs will be fairly small, so putting them in the main repo shouldn't be too much of a stretch.

Fair enough. Regardless of the location of the `.md` file, though, how would you feel about trying MyST for the documentation of a part of `sgkit`?

**Comment by hammer** [comment]
After some discussion on the [20200709 developer call](https://discourse.smadstatgen.org/t/20200709-developer-call-notes/63), we've decided to write docs in ReST, not MyST, for now.

We still have some decisions to make
- What docstring style will we adopt?
- What Sphinx extensions will we use?
- Where will we host the docs?

I'll do a bit more research and write up my findings for discussion next week.

**Comment by hammer** [comment]
Also be sure to run [doctest](https://docs.python.org/3/library/doctest.html) in our CI.

**Comment by hammer** [comment]
@jeromekelleher notes there are linters for docstrings too.

**Comment by jeromekelleher** [comment]
Some good links here:

https://pypi.org/project/flake8-rst-docstrings/

https://github.com/asottile/blacken-docs

**Comment by hammer** [comment]
https://github.com/jdillard/continuous-sphinx has some code for deploying Sphinx docs to Netlify, though they use Travis CI in place of GH Actions.

**Comment by hammer** [comment]
I think we can close this issue with #51 going in. Let me know if y'all think otherwise.
