### ISSUE TITLE
Standardize array type annotations in docstrings

### ISSUE THREAD

**Issue by eric-czech** [pystatgen/sgkit#216]
Here are a few conventions floating around the repo with minor differences in how arrays are documented:

From https://github.com/pystatgen/sgkit/blob/master/sgkit/stats/association.py#L26:

```
Parameters
----------
XL : (M, N) array-like
    "Loop" covariates for which N separate regressions will be run
XC : (M, P) array-like
    "Core" covariates included in the regressions for each loop
    covariate. All P core covariates are used in each of the N
    loop covariate regressions.
Y : (M, O)
    Continuous outcomes
```

From https://github.com/pystatgen/sgkit/blob/master/sgkit/stats/regenie.py#L610:

```
    Parameters
    ----------
    G : (M, N) ArrayLike
        Genotype data array, `M` samples by `N` variants.
    X : (M, C) ArrayLike
        Covariate array, `M` samples by `C` covariates.
    Y : (M, O) ArrayLike
        Outcome array, `M` samples by `O` outcomes.
    contigs : (N,) ArrayLike
```

From https://github.com/pystatgen/sgkit/blob/1a5885734020cc52847a3fdd327a35f4426aeb73/sgkit/api.py:

```
Parameters
----------
variant_contig_names : list of str
    The contig names.
variant_contig : array_like, int
    The (index of the) contig for each variant.
variant_position : array_like, int
    The reference position of the variant.
```

There are some situations where a data type for the array and shape information is relevant and other times that it's not.  I propose we standardize ```array_name : [shape_info] array_like[, dtype]```.  As an example, ```x : (M, N) array_like, int```.

When the "array_like" type needs to be more specific, e.g. a Dask array, I think we can still use "array_like" in the docstring and let a more specific type hint indicate the true bounds on inputs.

For reference, here is a random Dask [docstring snippet](https://github.com/dask/dask/blob/bdb7e906051b686207d8e1005f13962593be9797/dask/array/linalg.py#L954):

```
Parameters
----------
a : (M, M) array_like
    A triangular matrix
b : (M,) or (M, N) array_like
```

**Comment by tomwhite** [comment]
It would be worth understanding how this plays with [sphinx-autodoc-typehints](https://github.com/agronholm/sphinx-autodoc-typehints).

I also stumbled across [scanpydoc.elegant_typehints](https://icb-scanpydoc.readthedocs-hosted.com/en/latest/scanpydoc.elegant_typehints.html#module-scanpydoc.elegant_typehints) that may be useful for us too.

**Comment by aktech** [comment]
@tomwhite sphinx-autodoc won't interfere with the convention suggested by @eric-czech as since `array-like` is just a string and which can be anything which you can put in the `param`'s description. sphinx-autodoc will only pick the type hint to show, right next to the param name, for example:

<img width="767" alt="render" src="https://user-images.githubusercontent.com/5647941/92497216-585f1b00-f1f9-11ea-8da3-baaeccea9431.png">

Current view: https://pystatgen.github.io/sgkit/generated/sgkit.create_genotype_call_dataset.html

Also **scanpydoc.elegant_typehints** seems like a nice addition, the above rendered example includes that too. Anything that works with **sphinx-autodoc** will work with **scanpydoc.elegant_typehints** as well.

Another thing to note here is in the example I had to change the following (apart from adding the two extensions in the `conf.py`):

```diff
diff --git a/sgkit/api.py b/sgkit/api.py
index 3408b60..4b2acf9 100644
--- a/sgkit/api.py
+++ b/sgkit/api.py
@@ -25,33 +25,29 @@ def create_genotype_call_dataset(
 ) -> xr.Dataset:
     """Create a dataset of genotype calls.

-    Parameters
-    ----------
-    variant_contig_names : list of str
+    :param variant_contig_names: list of str
         The contig names.
-    variant_contig : array_like, int
+    :param variant_contig: array_like, int
         The (index of the) contig for each variant.
-    variant_position : array_like, int
+    :param variant_position: array_like, int
         The reference position of the variant.
-    variant_alleles : array_like, zero-terminated bytes, e.g. "S1", or object
+    :param variant_alleles: array_like, zero-terminated bytes, e.g. "S1", or object
         The possible alleles for the variant.
-    sample_id : array_like, str or object
+    :param sample_id: array_like, str or object
         The unique identifier of the sample.
-    call_genotype : array_like, int
+    :param call_genotype: array_like, int
         Genotype, encoded as allele values (0 for the reference, 1 for
         the first allele, 2 for the second allele), or -1 to indicate a
         missing value.
-    call_genotype_phased : array_like, bool, optional
+    :param call_genotype_phased: array_like, bool, optional
         A flag for each call indicating if it is phased or not. If
         omitted all calls are unphased.
-    variant_id: array_like, str or object, optional
+    :param variant_id: array_like, str or object, optional
         The unique identifier of the variant.

     Returns
     -------
-    :class:`xarray.Dataset`
         The dataset of genotype calls.
-
```

**Comment by tomwhite** [comment]
Thanks for investigating this @aktech, this is a good improvement. I wonder if it's possible to separate the type information and the definition on separate lines, like in https://scanpy.readthedocs.io/en/stable/api/scanpy.pp.calculate_qc_metrics.html#scanpy.pp.calculate_qc_metrics?

Also, have you got any suggestions for better type hints for the array-like parameters? Hopefully we can do better than `Any`.

**Comment by aktech** [comment]
> I wonder if it's possible to separate the type information and the definition on separate lines, like in https://scanpy.readthedocs.io/en/stable/api/scanpy.pp.calculate_qc_metrics.html#scanpy.pp.calculate_qc_metrics?

I think it should be, I'll have a look.

> Also, have you got any suggestions for better type hints for the array-like parameters? Hopefully we can do better than Any.

I think, we should be as explicit as we can in the type hints, like specifying exact set of expected types for params and return types. I see there is already an `ArrayLike` type object defined in here:

https://github.com/pystatgen/sgkit/blob/cd764bfc1f715dd69df6161a5f8043095b1e6586/sgkit/typing.py#L7

We should use these instead of `Any` and create new types in their if required and shape or data type information can go in the description as @eric-czech suggested.

**Comment by aktech** [comment]
@tomwhite Regarding separating the type information and the definition on separate lines, I was looking for an easy way to tweak any configuration values to get the desired result, but couldn't find any.

Then I was looking at how `scanpy` does it, as in which extension makes it possible. I found that the `scanpydoc` itself implements the same, so if we use the `scanpydoc` extension, we should get what we are looking for.

Here is the diff: https://github.com/pystatgen/sgkit/compare/master...aktech:doc-typehints?expand=1

<img width="777" alt="Screenshot 2020-09-10 at 15 59 54" src="https://user-images.githubusercontent.com/5647941/92741220-acdfd300-f37e-11ea-9461-4e5cea4c3d75.png">

.

**Comment by tomwhite** [comment]
A few comments on some of these:
* `variant_contig_names`: the "list of str" part is redundant so could be dropped.
* `variant_contig`: if the type was `ArrayLike`, then we would only have to indicate that the element type is `int` in the description. Perhaps this could just be in parentheses: "(element type: `int`) The index of the contig for each variant." Or it could go at the end of the description.
* `variant_id`: if the type was `Optional[ArrayLike]`, then this would render better.
