### ISSUE TITLE
Update popgen stats to compute for all variants

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit#238]
#100 added support for some basic popgen stats. However, these all currently return a single value, which contradicts the idiom that we are establishing of "every function returns an updated dataset" (#103). I think the default behaviour of these functions should be to return the full array of values in the updated dataset, for example, in the ``diversity`` function we'd add a new variable ``stats_diversity`` which is assigned the value of ``pi`` that we have computed (before summing).

This would include the Fst (#225) statistic, so is part of #232 and #226.

**Comment by tomwhite** [comment]
This was fixed in #303 and documented in #361
