### ISSUE TITLE
PC-Relate implementation

### ISSUE THREAD

**Issue by ravwojdyla** [pystatgen/sgkit#24]
Relevant discussion: https://discourse.smadstatgen.org/t/pc-relate-experiment/
Code: https://github.com/related-sciences/gwas-analysis/tree/rav-pc_relate

Potential plan could be:
 1. move the code+tests over here with adjustments for the sgkit API
 2. improve upon the implementation (this could be tracked as a separate issue(s))

We can use this issue to track the work necessary to move it over here.

**Comment by ravwojdyla** [comment]
@tomwhite I know you started reviewing the PC-Relate code - what's the state right now?

**Comment by tomwhite** [comment]
My focus was on the locating the performance bottlenecks in the PC-Relate code (brief notes here: https://github.com/related-sciences/gwas-analysis/blob/rav-pc_relate-tw/notebooks/platform/xarray/pc_relate_perf.py#L3-L7).

I think your plan makes sense - move the code over to this repo once the sgkit API becomes a bit clearer.

**Comment by ravwojdyla** [comment]
Thanks @tomwhite I see. Regarding perf/gramian issue, I thought it might also be interesting to try to represent it with optimised `einsum`, plus you've have mentioned potentially computing only the parts we are interested in, which is equally interesting! I bet there is lot we can improve - but yea, let's first move it in, and then optimise.

**Comment by ravwojdyla** [comment]
FYI: I will go ahead and create a PR for the current state.

**Comment by ravwojdyla** [comment]
Closing this via #228
