### ISSUE TITLE
Add windows CI

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit#247]
I think it would be a good idea to have windows CI setup before we implement the mono-repo (#65). 

Any takers?

**Comment by tomwhite** [comment]
We now use msprime for testing, so we'll need to install that on Windows. Do you think it's best to use a conda env to do that @jeromekelleher?

**Comment by jeromekelleher** [comment]
Hmm, yes, good point. Conda is really the only option on Windows for msprime  (and life generally easier on windows with conda). I'm guessing a lot of the stuff we want to use will be conda only on windows anyway.

**Comment by tomwhite** [comment]
I'm going to try using this GitHub Action to set up conda: https://github.com/marketplace/actions/setup-miniconda.

@ravwojdyla pointed out two other alternatives (https://github.com/s-weigand/setup-conda and https://github.com/fastai/workflows/tree/master/conda-env), but they don't seem to be as popular.
