### ISSUE TITLE
Stop using __all__ for top-level namespace

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit#251]
We seem to have a lot of "git conflict potential" in the current setup. The two main places seem to be in the ``known_third_party`` in setup.cfg and manually listing all API functions in ``__init__.py``. I can see how ``known_third_party`` will settle down after a while, but manually updating  ``__init__.py`` for every new function is going to lead to lots of conflicts and be pretty tedious for maintainers.

Is it worth keeping such a strict hold on the top-level namespace? People can still use undocumented methods by accessing the individual packages, so I've never really seen the point in manually managing the ``__all__`` variable.

**Comment by ravwojdyla** [comment]
I have looked into an alternatives to #294, and I start to lean more towards keeping both `__all__` and imports. The reasoning: without `__all__` global names are not reexported for type checking purposes unless we either specify mypy's `implicit_reexport` or change all imports to `import x as x` style ([doc](https://mypy.readthedocs.io/en/stable/config_file.html#confval-implicit_reexport)). Initially setting `implicit_reexport` in sgkit might seem like an attractive solution, but it would also force sgkit users (who use mypy) to either also set `implicit_reexport` or they might see mypy errors (missing symbols from sgkit inits). As mentioned above alternative to `__all__` could be the `import x as x` style, one issue with that solution is that the `__all__` approach has a bit better docstring support, for example `help(sgkit)` would include help for `__all__` symbols unlike the `import x as x` solution. Overall, at this point in time, in my mind, the user benefits are worth the sporadic PR conflicts.

**Comment by jeromekelleher** [comment]
OK, sounds good @ravwojdyla. Perhaps it's worth a quick comment in the top-level ``__init__.py`` explaining to developers why we're doing it this way? I feel like we'll be returning to this over and again as new contributors come along otherwise.

**Comment by ravwojdyla** [comment]
Closing via https://github.com/pystatgen/sgkit/pull/359
