### ISSUE TITLE
Remove create_*_dataset methods from public API

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#252]
As pointed out in https://github.com/pystatgen/sgkit/issues/243#issuecomment-691553120 these are not really public - they are used by the PLINK/BGEN/VCF reading functions, which is what users should use.

Also might be worth moving `simulate_genotype_call_dataset` to the top-level at the same time as it being in `testing` is an anomaly.

**Comment by eric-czech** [comment]
> Also might be worth moving simulate_genotype_call_dataset to the top-level at the same time as it being in testing is an anomaly.

+1

**Comment by eric-czech** [comment]
For posterity, `simulate_genotype_call_dataset` was move up in https://github.com/pystatgen/sgkit/pull/278.
