### ISSUE TITLE
Move sgkit-bgen to main sgkit repo

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#256]

**Comment by ravwojdyla** [comment]
@eric-czech would you like to do the honours of moving the sgkit-bgen to sgkit once pystatgen/sgkit-bgen#22 is in? It should be simply following the same pattern as #277, and I can assist/review if there are any issues/question. If not I am happy to take this.

**Comment by eric-czech** [comment]
> @eric-czech would you like to do the honours of moving the sgkit-bgen to sgkit once pystatgen/sgkit-bgen#22 is in?

Would be happy to, though it may take me a while to get to it (next week some time).
