### ISSUE TITLE
Publish documentation/build has been failing for 2 days

### ISSUE THREAD

**Issue by ravwojdyla** [pystatgen/sgkit#265]
https://github.com/pystatgen/sgkit/actions?query=workflow%3A%22Publish+documentation%22

Solution, we need to install GSL in that workflow as well.

Having badge would potentially help catch this earlier, thus related #264 

Somewhat related (but not really) #263

**Comment by jeromekelleher** [comment]
This is the simplest thing to do all right, but we could consider just installing what we need for doing docs building too? Pulling in the full dev stack might not be necessary/the best approach.

**Comment by ravwojdyla** [comment]
@jeromekelleher I hear you, given that you have spent most time with this, @tomwhite wdyt?

**Comment by tomwhite** [comment]
We could separate out the docs requirements from the one ones needed to run the tests. We don't need msprime/GSL for the former. (We might also remove the requirements files entirely, see #89.)

To fix the build, I think we should just add the GSL dependency for now. For the Windows CI build (#247) we are going to switch to conda, so this issue (GSL install) will go away, but #247 isn't ready yet.

**Comment by ravwojdyla** [comment]
@tomwhite fyi, added a comment about completely removing the `requirements` files in #89 

Otherwise, perfect, the PR is in #266

**Comment by ravwojdyla** [comment]
Closed via #266
