### ISSUE TITLE
Fresh pre-commit is failing on the master

### ISSUE THREAD

**Issue by ravwojdyla** [pystatgen/sgkit#275]
Needed to create a fresh conda env for sgkit dev, and fresh pre-commit env is failing on master with:

```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

sgkit/stats/utils.py:46: error: unused 'type: ignore' comment
sgkit/display.py:182: error: unused 'type: ignore' comment
sgkit/tests/test_association.py:135: error: unused 'type: ignore' comment
sgkit/tests/test_association.py:186: error: unused 'type: ignore' comment
sgkit/tests/test_association.py:188: error: unused 'type: ignore' comment
sgkit/tests/test_hwe.py:140: error: unused 'type: ignore' comment
sgkit/tests/test_regenie.py:190: error: unused 'type: ignore' comment
Found 7 errors in 5 files (checked 44 source files)
```

This doesn't seem to fail on GH, presumably because pre-commit is still using cache for its envs.

**Comment by eric-czech** [comment]
Hmm any idea why are these failing now if the mypy version hasn't ever been changed?

**Comment by ravwojdyla** [comment]
@eric-czech yea, the reason why this is failing on a new pre-commit env:
 * xarray 0.16.1 was released 3 days ago
 * pre-commit GH actions comes with cache built-in
 * since pre-commit config files have not changed in last 3 days, cache has not been invalidated yet, and our master is still testing against xarray 0.16.0

Does this makes sense?

**Comment by eric-czech** [comment]
Oo I see, so Xarray add some type hints.  Ty.
