### ISSUE TITLE
Genotype call array count alleles

### ISSUE THREAD

**Issue by alimanfoo** [pystatgen/sgkit#3]
Raising this issue to propose implementing a function to perform an allele count on a genotype array.

The input would be a [genotype call array](https://discourse.smadstatgen.org/t/n-d-array-conventions-for-variation-data/16/4?u=alimanfoo).

The output would be an [allele count array](https://discourse.smadstatgen.org/t/n-d-array-conventions-for-variation-data/16/7?u=alimanfoo).

The function summarises information across samples and ploidy dimensions, counting the number of observations of each allele index (0, 1, 2, etc.) for each variant.

**Comment by alimanfoo** [comment]
For reference, this was implemented in scikit-allel as [GenotypeArray.count_alleles()](https://scikit-allel.readthedocs.io/en/stable/model/ndarray.html#allel.GenotypeArray.count_alleles).

**Comment by tomwhite** [comment]
@alimanfoo are you working on this? I'm happy to put something together for discussion. (I added a few related comments in #11)

**Comment by alimanfoo** [comment]
Hi @tomwhite, very happy if you want to put something together here. (Otherwise it's probably the first thing I'd ask quansight to look at.)

**Comment by tomwhite** [comment]
Thanks @alimanfoo.

It looks like the actual method code has been written by @eric-czech in https://github.com/pystatgen/sgkit/issues/29#issuecomment-656071795. So the remaining work (if we are broadly happy with that API) is to think about dispatch. For that I think the method functions can take an optional `backend` parameter, as discussed in #11.

**Comment by hammer** [comment]
@alimanfoo @tomwhite now that #36 has been merged, can we close this issue and move discussion of performance and dispatch to more specific issues?
