### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#30]
There's no rush but at some point it would be useful to have a project logo.

We can look through the NumFOCUS [sponsored](https://numfocus.org/sponsored-projects) and [affiliated](https://numfocus.org/sponsored-projects/affiliated-projects) projects for inspiration.

[Open Logos](http://openlogos.org/) is a cool project from [Aras Atasaygın](https://twitter.com/arasatasaygin) to make logos available for free to OSS projects.

99designs also collects [examples](https://99designs.com/inspiration/logos/open-source) of OSS logos created by their community.

Open Source Design has a [jobs board](https://opensourcedesign.net/jobs/) that seems to be a good place to post a request for a logo.

**Comment by hammer** [comment]
https://www.irpf.design did the [new NumPy logo](https://mobile.twitter.com/numpy_team/status/1286977618156216326).

**Comment by hammer** [comment]
NumFOCUS pages for related projects
- [NumPy](https://numfocus.org/project/numpy)
- [Pandas](https://numfocus.org/project/pandas)
- [Xarray](https://numfocus.org/project/xarray)
- [Zarr](https://numfocus.org/project/zarr)

**Comment by hammer** [comment]
Okay I've started a 99designs contest at https://99designs.com/logo-design/contests/logo-software-used-make-sense-genetics-data-1033255/entries. This contest will run for 7 days.

**Comment by jeromekelleher** [comment]
Just so long as it doesn't involve a DNA double helix...

**Comment by hammer** [comment]
@jeromekelleher uh oh any reason in particular you don't want a double helix? I figured the NumPy logomark w/ a DNA symbol would be an easy approach...

**Comment by hammer** [comment]
Okay we are down to a [final 6](https://99designs.com/logo-design/contests/logo-software-used-make-sense-genetics-data-1033255/entries).

I'm going to work with the designers directly to iterate on these and hopefully pick one by Thursday.

If you have any opinions, now is the time to voice them!

**Comment by hammer** [comment]
We have a logo! @jeromekelleher I hope you don't hate it...

![image](https://user-images.githubusercontent.com/15233/95505423-4c8f8180-097c-11eb-81d6-4256e29778dd.png)

**Comment by hammer** [comment]
For future reference here are the logo files
[logo-logo-for-software-used-to.zip](https://github.com/pystatgen/sgkit/files/5357305/logo-logo-for-software-used-to.zip)

**Comment by jeromekelleher** [comment]
These look great @hammer, I love the logo! I was imagining something much more literal when knocking DNA helix logos.

One of the issues with logos that use DNA double helixes is people often get the [handedness](https://sandwalk.blogspot.com/2015/03/on-handedness-of-dna.html#:~:text=The normal form of DNA,of DNA is B-DNA). I don't think we have any sense of handedness here do we?
