### ISSUE TITLE
Add Python 3.9 in the CI

### ISSUE THREAD

**Issue by aktech** [pystatgen/sgkit#310]
Since Python 3.9 is released: https://docs.python.org/3/whatsnew/3.9.html

It would be good to start testing this in CI as early as we can, we should add something to mark this is **expected to fail**, but would be good to know what's failing.

**Comment by aktech** [comment]
Here are some failure, when I ran it on my branch: https://github.com/aktech/sgkit/runs/1225522394

**Comment by tirkarthi** [comment]
Raised an issue in bed-reader project for 3.9 wheels : https://github.com/fastlmm/bed-reader/issues/2

**Comment by tomwhite** [comment]
Is it worth trying this again @aktech? The dependencies should have Python 3.9 artifacts by now.

**Comment by aktech** [comment]
Yep, I have just started a run: https://github.com/aktech/sgkit/actions/runs/856418967

**Comment by hammer** [comment]
Should we also add 3.9 support to the docs before closing? Cf. https://pystatgen.github.io/sgkit/latest/getting_started.html#installation

**Comment by tomwhite** [comment]
I've got a change to make for conda packaging, so I can add it then.
