### ISSUE TITLE
Use logo and colors in docs

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#322]
[sgkit-logo.zip](https://github.com/pystatgen/sgkit/files/5357313/sgkit-logo.zip)
[BrandGuide.pdf](https://github.com/pystatgen/sgkit/files/5357314/BrandGuide.pdf)

**Comment by hammer** [comment]
While looking into how to customize Sphinx themes I noticed [Furo](https://github.com/pradyunsg/furo), a new theme for documentation that looks quite nice.

**Comment by aktech** [comment]
I think we can start with putting this logo on the [GitHub organization](https://github.com/pystatgen).

**Comment by hammer** [comment]
@aktech good call! Just put it up there. It's a little confusing given our org name is `pystatgen` but I'm into it.

**Comment by jeromekelleher** [comment]
Looks great

**Comment by hammer** [comment]
Another potential theme to consider https://github.com/bashtage/sphinx-material

**Comment by tomwhite** [comment]
Fixed in #501
