### ISSUE TITLE
Document our use of the S dtype for alleles

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#34]
I think @tomwhite and @alimanfoo have the state on this one.

**Comment by tomwhite** [comment]
#98 is related and will affect how we document allele dtype.

**Comment by tomwhite** [comment]
The `variant_allele` variable is documented to have dtype kind `S` or `O` here: https://pystatgen.github.io/sgkit/latest/generated/sgkit.variables.variant_allele_spec.html. So I think we can close this.
