### ISSUE TITLE
Method validation directory/repository

### ISSUE THREAD

**Issue by eric-czech** [pystatgen/sgkit#35]
A common need in implementing methods will be drawing comparisons to existing software.  Some of these comparisons may be approximate and others may be exact, but in either case we should ensure that these comparisons are reflected in unit tests.  

Any validations requiring software not in some approved list of dependencies (starting w/ @jeromekelleher's [suggestion](https://github.com/pystatgen/sgkit/issues/15#issuecomment-654275315) to at least allow tskit, scikit-allel, and pylibseq), need a place for the associated docker images, notebooks and scripts to live.   I'll propose that we start putting them in an `sgkit/validation` folder and see how it grows from there.

Also, I'm currently using scripts from these to produce arrays that I then copy+paste into unit tests.  It might eventually be worth putting more restrictions/automation around this so everything is easier to reproduce in the future.

**Comment by hammer** [comment]
> copy+paste into unit tests

Why not capture the output of these scripts in a file and point the tests at that file?

**Comment by tomwhite** [comment]
We now have a _validation_ directory.
