### ISSUE TITLE
Release 0.1.0a1

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#367]
This is an umbrella issue for our first release.

This would be an alpha [pre-release](https://www.python.org/dev/peps/pep-0440/#pre-releases) (suggested version number: 0.1.0a1), which means that users would have to opt in to use it by specifying the `--pre` flag: `pip install --pre sgkit`.

Here are some of the tasks we need to do - please suggest more (or say if they are not needed). 

- [ ] cyvcf2 wheel (should we wait for this?)
- [ ] Build release artifacts locally
- [ ] Add release number to documentation URL
- [ ] Use TestPyPI to test release process
- [ ] Update installation instructions for users
- [ ] Document release process

Note that these are all about what we need to do to make a release; since it's a pre-release, the exact set of features doesn't matter so much.

**Comment by hammer** [comment]
@jeromekelleher notes that `tskit` makes use of GH Actions to automate testing of installation of releases. @jeromekelleher can you point us to that?

**Comment by jeromekelleher** [comment]
Yep, [here](https://github.com/tskit-dev/tskit/blob/main/.github/workflows/wheels.yml) it is. This action builds the release artefacts on each pull request, does some basic tests on them to make sure they work, and uploads them to PyPI when a release is tagged.

**Comment by jeromekelleher** [comment]
Should be quite a bit simpler here since we're not actually compiling anything.

**Comment by horta** [comment]
I'm taking care of the cyvcf2 wheels. It is on test-pypi already. I will open a PR for Brent today. Meanwhile you can test it as follows.


Installing cyvcf2
-----------------

```
# coloredlogs is not on test-pypi
pip install coloredlogs
```

```
# numpy wheels are on pypi
pip install numpy
```

```
# Our testing distribution
pip install -i https://test.pypi.org/simple/ cyvcf2
```

The following should then work:

`cyvcf2 --help`

Platforms: MacOS, Linux
Python: 3.5, 3.6, 3.7., 3.8, 3.9

Related issues
--------------

https://github.com/pystatgen/sgkit/issues/327
https://github.com/pystatgen/sgkit/issues/367

**Comment by horta** [comment]
I've just opened a PR: https://github.com/brentp/cyvcf2/pull/175

**Comment by hammer** [comment]
Thanks @horta! By the way, I recently learned about [abi3](https://twitter.com/codewithanthony/status/1324066293557833728) that can be used to make wheels more portable. Have you heard of it or tried it out? I expect it's not going to be useful for something like `cyvcf2` but for the simpler BED and BGEN readers perhaps it could save you some time?

**Comment by horta** [comment]
Never heard of. Thanks!

**Comment by jeromekelleher** [comment]
Good to know about abi3 @hammer, thanks!

**Comment by jeromekelleher** [comment]
Woot! Install worked for me on Python 3.8, Linux Mint. Awesome work @horta!

**Comment by horta** [comment]
I'm glad =)

**Comment by tomwhite** [comment]
I have built the sgkit test artifacts and released to TestPyPI: https://test.pypi.org/project/sgkit/0.1.0a1/, which should be ready for testing.

You can install the main package with

```bash
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple --pre sgkit
```

(The `--extra-index-url` is needed since some of sgkit's dependencies are not on TestPyPI, and pip needs to be told to get them from regular PyPI.)

Extras are installed in a similar way:

```bash
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple --pre 'sgkit[bgen]'
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple --pre 'sgkit[plink]'
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple --pre 'sgkit[vcf]'
```

The changes needed for the release are in #376. I'll write up some release instructions too.

BTW I successfully picked up @horta's cyvcf2 wheels from TestPyPi when installing `sgkit[vcf]` on Mac, and ran a small VCF test. Thanks for your work on this @horta!

```
Collecting cyvcf2; extra == "vcf" (from sgkit[vcf])
  Downloading https://test-files.pythonhosted.org/packages/44/ee/816bf6dad913a314dc4fda67f08a8077bd7e14747b2701672e5c3d24f763/cyvcf2-0.20.10-cp37-cp37m-macosx_10_9_x86_64.whl (2.9MB)
```

**Comment by tomwhite** [comment]
### Release instructions

(These instructions will be updated here for this release - they may be added to the Sphinx docs later, but it's likely they will change since we would like to drive releases from CI in future.)

With the latest branch checked out locally, build the artifacts with:

```bash
VERSION=0.1.0a1
git tag $VERSION
rm -rf build dist; python setup.py sdist bdist_wheel
```

Test locally by installing as follows in a new virtualenv (and running some sgkit functions to sanity check):

```bash
pip install ../sgkit/dist/sgkit-0.1.0a1-py3-none-any.whl
pip install ../sgkit/dist/sgkit-0.1.0a1-py3-none-any.whl[bgen]
pip install ../sgkit/dist/sgkit-0.1.0a1-py3-none-any.whl[plink]
pip install ../sgkit/dist/sgkit-0.1.0a1-py3-none-any.whl[vcf]
```

Upload to TestPyPI

```bash
pip install twine
twine upload --repository testpypi dist/*
open https://test.pypi.org/project/sgkit/$VERSION/
```

Test in a new virtualenv

```bash
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple --pre sgkit
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple --pre 'sgkit[bgen]'
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple --pre 'sgkit[plink]'
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple --pre 'sgkit[vcf]'
```

Remaining steps:
* Upload to PyPI
* Test
* Update docs
  * I suggest we publish docs for this release at https://pystatgen.github.io/sgkit/0.1.0a1/, and change the automatically generated docs for the main branch to https://pystatgen.github.io/sgkit/latest/.
* Push tag to github

**Comment by hammer** [comment]
Very cool @tomwhite!

One question about release artifact tests: do we exercise the remote read path for `cyvcf2` that failed for the current version of the Linux wheels?

**Comment by tomwhite** [comment]
> One question about release artifact tests: do we exercise the remote read path for `cyvcf2` that failed for the current version of the Linux wheels?

No, I haven't tested that. I've just been doing very light ad hoc testing so far, but I can give that a go (on Mac).

**Comment by jeromekelleher** [comment]
Safest way to test this I guess would be to set up a local HTTP server which we use during unit tests. We could use something like [this](https://github.com/ga4gh/htsget/blob/master/tests/test_local_server.py)

**Comment by tomwhite** [comment]
Yes, it works:

```python
from sgkit.io.vcf import vcf_to_zarr
vcf_to_zarr("https://github.com/pystatgen/sgkit/raw/master/sgkit/tests/io/vcf/data/sample.vcf.gz", "out")
```

**Comment by hammer** [comment]
For the upload to PyPI step, I happened to see https://github.com/pypa/gh-action-pypi-publish today, which may be useful for us.

**Comment by tomwhite** [comment]
Thanks @hammer - that will be useful we we get to automated releases.

**Comment by tomwhite** [comment]
The [0.1.0.a1 release](https://github.com/pystatgen/sgkit/releases/tag/0.1.0a1) is now on [PyPI](https://pypi.org/project/sgkit/0.1.0a1/) and can be installed with

    pip install --pre sgkit

Extras can be installed with

    pip install --pre 'sgkit[bgen]'
    pip install --pre 'sgkit[plink]'
    pip install --pre 'sgkit[vcf]'

Documentation is at https://pystatgen.github.io/sgkit/0.1.0a1/.

I've updated the release instructions in this issue.

**Comment by hammer** [comment]
Very cool! With Python 3.8 on macOS Catalina, I was able to install all of the packages.

I hit an issue trying to install with Python 3.9, though. It appears that [NumPy only recently added 3.9 wheels](https://github.com/numpy/numpy/issues/17482), but I'm not sure why `pip` wouldn't pick them up? I'm probably doing something dumb.

<details>
<summary>Error message</summary>

```
C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /usr/local/anaconda3/envs/sgkit/include -arch x86_64 -fPIC -O2 -isystem /usr/local/anaconda3/envs/sgkit/include -arch x86_64

compile options: '-Ibuild/src.macosx-10.9-x86_64-3.9/numpy/core/src/npymath -Inumpy/core/include -Ibuild/src.macosx-10.9-x86_64-3.9/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/local/anaconda3/envs/sgkit/include/python3.9 -Ibuild/src.macosx-10.9-x86_64-3.9/numpy/core/src/common -Ibuild/src.macosx-10.9-x86_64-3.9/numpy/core/src/npymath -Ibuild/src.macosx-10.9-x86_64-3.9/numpy/core/src/common -Ibuild/src.macosx-10.9-x86_64-3.9/numpy/core/src/npymath -c'
      llvm-ar: adding 4 object files to build/temp.macosx-10.9-x86_64-3.9/libnpymath.a
      error: Command "/opt/concourse/worker/volumes/live/8e75f32a-160a-4528-66de-c3389541e339/volume/python-split_1605449976272/_build_env/bin/llvm-ar rcs build/temp.macosx-10.9-x86_64-3.9/libnpymath.a build/temp.macosx-10.9-x86_64-3.9/numpy/core/src/npymath/npy_math.o build/temp.macosx-10.9-x86_64-3.9/build/src.macosx-10.9-x86_64-3.9/numpy/core/src/npymath/ieee754.o build/temp.macosx-10.9-x86_64-3.9/build/src.macosx-10.9-x86_64-3.9/numpy/core/src/npymath/npy_math_complex.o build/temp.macosx-10.9-x86_64-3.9/numpy/core/src/npymath/halffloat.o" failed with exit status 127
      ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/anaconda3/envs/sgkit/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tz/1_mlmz691xz8kkjx6x2s2l340000gn/T/pip-install-a3_tofwo/numpy/setup.py'"'"'; __file__='"'"'/private/var/folders/tz/1_mlmz691xz8kkjx6x2s2l340000gn/T/pip-install-a3_tofwo/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tz/1_mlmz691xz8kkjx6x2s2l340000gn/T/pip-record-qphmc84d/install-record.txt --single-version-externally-managed --prefix /private/var/folders/tz/1_mlmz691xz8kkjx6x2s2l340000gn/T/pip-build-env-wpso7jlo/overlay --compile --install-headers /private/var/folders/tz/1_mlmz691xz8kkjx6x2s2l340000gn/T/pip-build-env-wpso7jlo/overlay/include/python3.9/numpy Check the logs for full command output.
----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/anaconda3/envs/sgkit/bin/python /usr/local/anaconda3/envs/sgkit/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/tz/1_mlmz691xz8kkjx6x2s2l340000gn/T/pip-build-env-wpso7jlo/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --pre -- setuptools wheel 'Cython>=0.28.5' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation == '"'"'CPython'"'"'' 'numpy==1.14.0; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"' and platform_python_implementation != '"'"'CPython'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'scipy>=0.19.1' Check the logs for full command output.
```

</details>

**Comment by tomwhite** [comment]
Thanks for trying out the packages @hammer. I haven't tried installing with Python 3.9 - let's investigate that in #310.

> Is the former step still required?

Ah no - that line needs removing - I'll take care of that.

**Comment by hammer** [comment]
>let's investigate that in #310 

Makes sense!

Perhaps implicit in my attempt to install with Python 3.9 is the need for copying or moving our [supported versions text](https://pystatgen.github.io/sgkit/0.1.0a1/contributing.html?highlight=python%203%208#python-versions) from the contributing section into the getting started section.

**Comment by tomwhite** [comment]
Good point. I'll create a PR to improve the documentation in this area.

**Comment by hammer** [comment]
Just confirmed the release works with Python 3.8 and Ubuntu 18.04 as well, again with the caveat that I didn't try to read any files.

I did notice on Ubuntu that some packages had a build step that I did not notice on macOS: `pyyaml`, `asciitree`, `psutil`. It looks like https://github.com/yaml/pyyaml/pull/407 might add wheels soon for `pyyaml`, and `psutil` just needs to publish theirs https://github.com/giampaolo/psutil/issues/1864. I just sent some +1s to those issues, maybe y'all can do them too?

I was surprised at the high latency for `import sgkit`. Is that because of numba? Is there anything we can do to bring that time down?

**Comment by horta** [comment]
Happy to see `sgkit` growing so fast =)

I've instructed brentp on how to release wheels: https://github.com/brentp/cyvcf2/pull/175 So I guess there is not much I can do right now regarding cyvcf2.

**Comment by tomwhite** [comment]
> I did not confirm that reading data from files works though--it would be nice if we hosted or shipped small sample files for users to test out their installation (maybe we already do?).

Here are some commands to manually test the IO readers. They could be moved to tests or documentation at some point.

### BGEN
```bash
wget https://github.com/pystatgen/sgkit/raw/master/sgkit/tests/io/bgen/data/example.bgen
```

```python
from sgkit.io.bgen import read_bgen
ds = read_bgen("example.bgen")
print(ds)
```

### PLINK
```bash
wget https://github.com/pystatgen/sgkit/raw/master/sgkit/tests/io/plink/data/plink_sim_10s_100v_10pmiss.bed
wget https://github.com/pystatgen/sgkit/raw/master/sgkit/tests/io/plink/data/plink_sim_10s_100v_10pmiss.bim
wget https://github.com/pystatgen/sgkit/raw/master/sgkit/tests/io/plink/data/plink_sim_10s_100v_10pmiss.fam
```

```python
from sgkit.io.plink import read_plink
ds = read_plink(path="plink_sim_10s_100v_10pmiss")
print(ds)
```

### VCF
```python
from sgkit.io.vcf import vcf_to_zarr
import xarray as xr
vcf_to_zarr("https://github.com/pystatgen/sgkit/raw/master/sgkit/tests/io/vcf/data/sample.vcf.gz", "out")
ds = xr.open_zarr("out")
print(ds)
```

**Comment by hammer** [comment]
Thanks @tomwhite, reading BGEN and PLINK seems to work with Python 3.8 Ubuntu 18.04. I'm still waiting on `htslib` to build so that I can test VCF reading. I can't wait until we have wheels!
