### ISSUE TITLE
Genotype call visualization function

### ISSUE THREAD

**Issue by eric-czech** [pystatgen/sgkit#37]
Understanding the content of 3D (variants, samples, ploidy) call arrays is difficult and we should add something that makes the calls more readable, like [GenotypeArray](https://scikit-allel.readthedocs.io/en/stable/model/ndarray.html?highlight=genotypearray#allel.GenotypeArray) does.

Here is a quick example within Xarray/Pandas:

```python
ds['call/genotype'].to_series().unstack().astype(str).apply('/'.join, axis=1).unstack()
samples  0      1
variants
0        1/0	1/0
1        1/0	1/1
2        0/1	1/0
3        0/0	0/0

**Comment by alimanfoo** [comment]
For API how about: 

``sgkit.display_genotypes(ds : Dataset) -> GenotypeDisplay``

...where ``GenotypeDisplay`` is a class that implements at least ``__repr__`` and ideally also ``_repr_html_()``. Would allow for text display in terminal and HTML table display in notebook.
