### ISSUE TITLE
Ploidy arguments are not passed on to vcf_to_zarr_parallel

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#409]
In `vcf_to_zarr` the ploidy arguments are not passed to `vcf_to_zarr_parallel` - they are only passed to `vcf_to_zarr_sequential`.

cc @timothymillar

**Comment by timothymillar** [comment]
Thanks @tomwhite 

I've possibly run into another bug while testing a fix for this.
The variant allele values are read in the wrong shape/dtype if I use regions:

Without using regions:
```python
vcf_to_zarr(
    '../sgkit/sgkit/tests/io/vcf/data/mixed.vcf.gz',
    'test.zarr', 
    ploidy=4, 
    mixed_ploidy=True, 
)
ds = xr.open_zarr('test.zarr')
ds.variant_allele.values
```
Results in:
```
array([['A', 'T', '', ''],
       ['A', 'C', '', '']], dtype=object)
```

With regions:
```python
vcf_to_zarr(
    '../sgkit/sgkit/tests/io/vcf/data/mixed.vcf.gz',
    'test.zarr', 
    ploidy=4, 
    mixed_ploidy=True, 
    regions=['CHR1:0-5', 'CHR1:5-10'],
)
ds = xr.open_zarr('test.zarr')
ds.variant_allele.values
```
Results in:
```
array([b'AT', b'AC'], dtype='|S4')
```

This may be an xarray issue because zarr opens it with the correct dtype/shape:
```python
zarr.open('test.zarr', 'r')['variant_allele'][:]
```
Results in
```
array([[b'A', b'T', b'', b''],
       [b'A', b'C', b'', b'']], dtype='|S1')
```

**Comment by tomwhite** [comment]
Yes, it's a known problem with xarray. If you use ```xr.open_zarr('test.zarr', concat_characters=False)``` it will work.

We've recently introduced the convenience functions `load_dataset` and `save_dataset` in sgkit to handle this:

```python
>>> vcf_to_zarr(
        '../sgkit/sgkit/tests/io/vcf/data/mixed.vcf.gz',
        'test.zarr', 
        ploidy=4, 
        mixed_ploidy=True, 
        regions=['CHR1:0-5', 'CHR1:5-10'],
    )
>>> ds = sg.load_dataset('test.zarr')
>>> ds.variant_allele.values
array([[b'A', b'T', b'', b''],
       [b'A', b'C', b'', b'']], dtype='|S1')
```

Thanks for looking at this issue.
