### ISSUE TITLE
Run build on a schedule

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#422]
We should run the build daily to pick up changes to dependencies that cause our tests to fail (like #421).

**Comment by ravwojdyla** [comment]
Somewhat related: dask has an "upstream" CI build, which is an interesting take on this problem, it essentially run dask CI with main/master versions of some of the core dependencies. They run this on schedule as well as on master changes. This could be valuable for us to detect breaking changes before releases. See the upstream CI definition [here](https://github.com/dask/dask/blob/master/.github/workflows/ci-upstream.yml).
