### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit#427]
In the meeting 17/12/20 we decided that a conda package is something that many users need, and we should provide one. The most straightforward approach is to create a conda-forge package for sgkit which depends on the core upstream components. The main problem is that the IO packages that we depend on aren't in conda-forge, and so users will need to work around this. However, these are all optional imports that will give good error messages, so this shouldn't be too bad.

I think we need to wait until we have a stable version released before we can make a conda-forge package, so parking this until we have a non-alpha release on pypi.

**Comment by jeromekelleher** [comment]
As an update on this, it seems better to create a Bioconda package since we have dependencies that are not in conda-forge. I'll report back once I've started making the package after #495.

**Comment by jeromekelleher** [comment]
Initial PR open on bioconda here: https://github.com/bioconda/bioconda-recipes/pull/27844

It'll probably take a while to get the details ironed out, I'll report back here once there's any information.

**Comment by jeromekelleher** [comment]
This worked better than I had hoped. The only issue seems to be that we don't have any conda package for bed-reader.  Long-term we would want to get a conda package for bed-reader, but I would suggest we go ahead and ask to merge the current bioconda package and get some testing done on it. We can see how our experience of using it goes (I'm not convinced we won't hit gnarly issues to do with numpy versions etc).

**Comment by jeromekelleher** [comment]
There's a bit of a quirk with bed-reader, since it's partly written in Rust but it looks like there's a few bioconda packages that use ``maturin`` already, so maybe making a package wouldn't be so hard.

**Comment by jeromekelleher** [comment]
So, a summary. We have two options: (1) a conda-forge package or (2) a bioconda package. There are pros and cons to both:

- Bioconda means that we can natively package everything as conda (assuming we can make a bioconda/conda-forge package for bed-reader); but
- conda-forge has better tooling, doing things like automatically issuing PRs when a package is issued to PyPI. There is also much better control of automatic pinning, which might become important with things like Dask etc.

Presumably, if we had a conda-forge package we would need to tell users who want to use VCF that they'd need to install ``cyvcf2`` using pip.

So, I think there's a tradeoff here between integration with packaging for the VCF functionality and the integration with packaging for big upstream packages like numba, xarray, Dask etc. It's not obvious to me what will lead to the best user experience in the long run, but I suspect the tighter integration with conda-forge packaging would lead to fewer "major" issues where stuff just flat out stops working. :shrug:

**Comment by jeromekelleher** [comment]
@eric-czech, @alimanfoo, @aktech - you're all conda users I believe, any thoughts here?

**Comment by eric-czech** [comment]
+1 to conda-forge, though I don't have a very smart reason for as much; I just rarely expect anything I install from bioconda to work well.

**Comment by hammer** [comment]
> The only issue seems to be that we don't have any conda package for bed-reader.

@CarlKCarlK has been very easy to work with, I’m sure he’d be open to working with us to get a conga package together.

Thanks for getting this started @jeromekelleher!

**Comment by CarlKCarlK** [comment]
Yes, I'm happy to have bed-reader be a conda package. What are the steps in making this happen?


  *   Carl

**Comment by jeromekelleher** [comment]
@CarlKCarlK - the simplest thing would be for me to start the process of creating a conda-forge package for bed-reader, and ping you once I've figured things out and it's ready for final review and merging. Once the initial package is built, the maintenance is very straightforward (really just "approving" an auto update PR and clicking merge, the vast majority of the time), so hopefully you'd be happy to share some of this with me?

(I'm suggesting conda-forge as the home for the bed-reader package, as this gives the most flexibility. This doesn't solve the problem about where sgkit's package should live, but I think that's an issue we'd need to go over in person.)

**Comment by CarlKCarlK** [comment]
All sounds good. I'm happy to take over maintenance once we get it going.

**Comment by jeromekelleher** [comment]
Great, thanks @CarlKCarlK. Initial work going on over at https://github.com/conda-forge/staged-recipes/pull/14471

**Comment by jeromekelleher** [comment]
Update: we have a conda-forge package for bed-reader!

https://github.com/conda-forge/bed-reader-feedstock
https://anaconda.org/conda-forge/bed-reader

:tada:

**Comment by hammer** [comment]
> if we had a conda-forge package we would need to tell users who want to use VCF that they'd need to install cyvcf2 using pip.

What can we do to remove this obstacle? Is there some upstream work we can do to get `cyvcf2` into conda-forge?

**Comment by jeromekelleher** [comment]
> What can we do to remove this obstacle? Is there some upstream work we can do to get cyvcf2 into conda-forge?

It's not to be taken lightly, as it involves packaging htslib for conda-forge. This shouldn't be done without engaging the htslib developers. Ultimately this would be a good thing, I think, and I would be willing to do some legwork and talk to the relevant people, but we shouldn't expect it to happen quickly.

**Comment by jeromekelleher** [comment]
On the call 2021-04-15 we decided to go with a conda-forge package. I'll report back when there's progress.

**Comment by jeromekelleher** [comment]
The initial PR has just been merged, so we should have a feedstock repo and a package in the next few hours.

**Comment by jeromekelleher** [comment]
https://github.com/conda-forge/sgkit-feedstock

https://anaconda.org/conda-forge/sgkit

**Comment by jeromekelleher** [comment]
Could we get some conda users to try out the package please? I think we can close the issue then.

**Comment by jmarshall** [comment]
> It's not to be taken lightly, as it involves packaging htslib for conda-forge. This shouldn't be done without engaging the htslib developers. Ultimately this would be a good thing, I think

A large number of packages in bioconda depend on HTSlib. Due to limitations in the _current_repodata.json_ implementation, conda does not track cross-channel dependencies well. See conda/conda#9905 and bioconda/bioconda-recipes#24199 for details. Thus moving HTSlib from bioconda to conda-forge while this conda limitation exists would cause great inconvenience for users (who would increasingly be offered old versions of downstream packages by default) and is therefore a nonstarter.

There does not appear to be much interest from the conda people in fixing this limitation.

See https://github.com/bioconda/bioconda-recipes/issues/24199#issuecomment-758553486 item (2) for a vaguely feasible workaround for this, though I expect there are other disadvantages. IMHO the people to engage would be the bioconda maintainers with an interest in HTSlib. Personally I would not expect there to be much appetite for moving HTSlib to conda-forge.

**Comment by jeromekelleher** [comment]
Thanks very much for the information @jmarshall, this is extremely helpful. I was actually about to reach out to you about this to get your thoughts, so you beat me to it!

After thinking about it more, I agree that moving htslib to conda-forge would be very messy and likely result in a lot of breakage. It seems like there are probably better things for us all to do...

**Comment by jeromekelleher** [comment]
Closing this as we now have a conda-forge package: https://anaconda.org/conda-forge/sgkit
