### ISSUE TITLE
Make a new release to pick up cyvcf2 wheels

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#431]

**Comment by jeromekelleher** [comment]
Do we need to? We're not pinned on a particular version of cyvcf2 in setup.cfg , so any new installs should use the wheels, if available.

**Comment by tomwhite** [comment]
Agreed a new release shouldn't be needed just for cyvcf2. I'm working on getting cyvcf2 wheels published here: https://github.com/brentp/cyvcf2/pull/186

**Comment by hammer** [comment]
😳 sorry for my ignorance!
