### ISSUE TITLE
Is test_vcfzarr_to_zarr test flaky?

### ISSUE THREAD

**Issue by aktech** [pystatgen/sgkit#457]
There was a test failure here: test_vcfzarr_to_zarr: https://github.com/pystatgen/sgkit/runs/1835950760?check_suite_focus=true

It disappeared when I triggered the build again and I haven't been able to reproduce it locally.
cc @tomwhite 

Feel free to close it, if unable to reproduce.

**Comment by tomwhite** [comment]
Thanks for reporting this @aktech. This is a duplicate of #388. I haven't seen it so often recently, but it appears to still be happening occasionally.
