### ISSUE TITLE
Setup air speed velocity for micro benchmarks

### ISSUE THREAD

**Issue by aktech** [pystatgen/sgkit#458]
As discussed in the developer call it would be good to have some kind of benchmarking. Air speed velocity is a good tool for micro benchmarks: https://asv.readthedocs.io/en/stable/ as suggested.

Setting this up and throwing the artefacts somewhere will enable us to see the benchmarks over time like this:
https://pv.github.io/numpy-bench/

cc @jeromekelleher

**Comment by jeromekelleher** [comment]
See also #68 - should we mark this issue as a dupe @hammer, or keep it as more specific?

**Comment by tomwhite** [comment]
Reopening, as the benchmark suite has not had a successful run yet.

**Comment by aktech** [comment]
This is quite weird, this works on my personal and organization accounts:

https://github.com/AktechLabs/sgkit/runs/2111770945?check_suite_focus=true
https://github.com/aktech/sgkit/runs/2039205063?check_suite_focus=true

@hammer Can you confirm the following.

1.  This is how the access token scope looks like:

<img width="805" alt="Screenshot 2021-03-15 at 11 36 59" src="https://user-images.githubusercontent.com/5647941/111147873-dcb4a100-8582-11eb-912b-618cb51c1dba.png">

2. You added the token named `GH_TOKEN`, in this (pystatgen/sgkit) repository.
3. You have push access to `pystatgen/sgkit-benchmarks-asv` repository.

**Comment by hammer** [comment]
I added it to the `pystatgen/sgkit-benchmarks-asv` repo. Is that not right?

**Comment by aktech** [comment]
> I added it to the pystatgen/sgkit-benchmarks-asv repo. Is that not right?

Oh, I see. The token needs to be in this repo: pystatgen/sgkit 
Apologies, the instructions I sent probably did not stated the repo name explicitly.

**Comment by hammer** [comment]
Okay, try now?

**Comment by aktech** [comment]
I don't have the access to rerun a workflow. Can one of you rerun this workflow?
https://github.com/pystatgen/sgkit/runs/2114712818

<img width="287" alt="Screenshot 2021-03-15 at 21 40 17" src="https://user-images.githubusercontent.com/5647941/111224958-0c8d9400-85d7-11eb-91ed-73258254b6ab.png">

**Comment by jeromekelleher** [comment]
I just reran it @aktech, can you have a look and see if it succeeded?

**Comment by aktech** [comment]
Yes, it did succeed. Thanks @hammer and @jeromekelleher 

Now, there is one last thing that needs to be done for the benchmarks to be visible on the Github pages on this link: http://pystatgen.github.io/sgkit-benchmarks-asv/

1. Go to https://github.com/pystatgen/sgkit-benchmarks-asv/settings
2. In the Github Pages section, select the source branch to be main and
3. Check the **Enforce HTTPS** button

**Comment by jeromekelleher** [comment]
Done! Thanks for the guide @aktech

**Comment by jeromekelleher** [comment]
@tomwhite, I guess we should confirm a few uploads of benchmarks before closing?

**Comment by aktech** [comment]
Thanks! the benchmarks is live now: https://pystatgen.github.io/sgkit-benchmarks-asv/

**Comment by tomwhite** [comment]
Looks good. Thanks for doing this @aktech. Would it be possible to add a badge to the README with a link to the benchmarks?

**Comment by aktech** [comment]
> Looks good. Thanks for doing this @aktech. Would it be possible to add a badge to the README with a link to the benchmarks?

Yeah, sure.

Can someone add this link: https://pystatgen.github.io/sgkit-benchmarks-asv/
In the about section of https://github.com/pystatgen/sgkit-benchmarks-asv as well


<img width="375" alt="Screenshot 2021-03-17 at 09 37 28" src="https://user-images.githubusercontent.com/5647941/111446515-66d84300-8704-11eb-9f19-75fc4d256261.png">

**Comment by hammer** [comment]
> Can someone add this link: https://pystatgen.github.io/sgkit-benchmarks-asv/
In the about section of https://github.com/pystatgen/sgkit-benchmarks-asv as well

Done!

**Comment by hammer** [comment]
Closing this issue as discussed on the call today. Thanks @aktech!
