### ISSUE TITLE
Cohort observed Heterozygosity

### ISSUE THREAD

**Issue by timothymillar** [pystatgen/sgkit#499]
In diploids the observed heterozygosity at a locus is typically described as the proportion of individuals who are heterozygous. This is generalised to polyploids in Hardy 2016 ([paper](https://onlinelibrary.wiley.com/doi/abs/10.1111/1755-0998.12431)) who defines the individual heterozygosity at a locus as the probability of drawing a pair of IBS alleles without replacement. For diploids this results in a value of 1.0 (het) or 0.0 (hom) and for ployploids it a values in the interval [0, 1]. Observed heterozygosity is then calculated as the mean of individual heterozygosities.

Individual and observed heterozygosity could be implemented as a pair of functions returning "call_heterozygosity" and "cohort_heterozygosity" respectively. Note that the above paper contains some examples suitable for unit tests.

Some related discussion on the [pystatgen discourse](https://discourse.pystatgen.org/t/calculation-of-expected-and-observed-heterozygosity/89).

**Comment by jeromekelleher** [comment]
Sounds good to me @timothymillar - are you volunteering to implement? :wink:
