### ISSUE TITLE
Implement REGENIE

### ISSUE THREAD

**Issue by eric-czech** [pystatgen/sgkit#50]
As a genetic association modeling framework, [REGENIE](https://github.com/rgcgithub/regenie) has a lot of very desirable properties for us.  It's one of very few that I've seen that addresses LD, sample correlation, multiple phenotypes and proximal contamination in a way that does not require iterative algorithms or explicit computation of either a kinship matrix or it's eigendecomposition (or some approximation of them).

The initial goal of REGENIE, much like other more recent frameworks, is to first fit a polygenic model across the genome (or perhaps all chromosomes but one) as a means to create accurate phenotype predictions.  These predictions are then subtracted from the original values and p-values are then generated based on those residuals -- which bridges the gap between ML modeling and frequentist sampling statistics.  REGENIE's choice for an ML model is simply a ridge regressor stack and though some of the details are tricky, there are some nice computational shortcuts that go into making the cross validation for this efficient and expressible through only common linear algebra operators.

I wasn't sure how well the [Glow implementation](https://glow.readthedocs.io/en/latest/tertiary/whole-genome-regression.html) would map to the Dask array API but I gave it a shot in [regenie.py](https://github.com/eric-czech/sgkit/blob/regenie/sgkit/stats/regenie.py) and managed to get nearly perfect matches to Glow results using a small simulated dataset.  

If anybody has any general style suggestions for that code, I'd definitely appreciate them now before it grows much more. 
 Otherwise I'll keep chugging away on it and see what it leads to.

----

Side note: It would be very difficult (and definitely awkard) to write a numpy-only backend for this because the algorithm isn't actually defined for single chunk arrays.  The cross validation is tightly coupled to the block sizes and you can't do it with <2 folds so a numpy version of this would need to work on at least 4D, and maybe as many as 8D arrays in some sections, to handle all the blockwise aggregations.

**Comment by tomwhite** [comment]
This looks great @eric-czech!

I haven't looked in detail, but it would be good to map this implementation to the original as closely as possible using the same variable names, and links to the original paper at as fine-grained a level as is possible. I like the practice you're using of adding assertions after every major linear algebra operation too.

**Comment by tomwhite** [comment]
Fixed in #66
