### ISSUE TITLE
Add Algolia DocSearch to our site

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#504]
https://docsearch.algolia.com/

I've already applied, they're going to send me a JS snippet to put on our site to enable indexing. We should get a nice typeahead for our search box once this goes live.

**Comment by jeromekelleher** [comment]
Nice, looking forward to seeing the results.

**Comment by hammer** [comment]
For future reference here are the docs on getting it set up https://docsearch.algolia.com/docs/dropdown.

**Comment by hammer** [comment]
DocSearch is ready! I will see if I can do the integration myself...

**Comment by hammer** [comment]
I got a note from Algolia on September 9 saying that they're going to stop crawling our site on September 23 if we don't get search implemented before then.

I took a look at the integration and it's non-trivial. There's some discussion on search, Algolia, Sphinx, and the RTD theme:
- https://github.com/sphinx-doc/sphinx/issues/3812
- https://github.com/executablebooks/jupyter-book/issues/1242
- https://github.com/executablebooks/jupyter-book/issues/1324
- https://github.com/readthedocs/sphinx_rtd_theme/issues/761

Unfortunately I don't see any discussion specific to our theme https://github.com/executablebooks/sphinx-book-theme.

The Algolia email:
```
Copy the following CSS/JS snippets and add them to your page

<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
apiKey: '<REDACTED>',
indexName: 'sgkit',
inputSelector: '### REPLACE ME ####',
debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

**Comment by hammer** [comment]
I spent a bit of time yesterday and today figuring this out and I have hit the limits of my frontend knowledge. I filed https://github.com/executablebooks/sphinx-book-theme/issues/394 upstream, so hopefully some kind soul will reply there.

**Comment by hammer** [comment]
Lol turns out that worked, I just needed to clear some cache. If y'all think a slightly ugly and suboptimal typeahead is a good idea, let's try it out. If not, we can put this on hold for a bit until we get some styling hints.

In addition to styling, I also think we'll want to exclude the index from being crawled and searched, since it generates duplicate entries in the typeahead.

**Comment by hammer** [comment]
To customize the crawling process, we can modify https://github.com/algolia/docsearch-configs/blob/master/configs/sgkit.json.
