### ISSUE TITLE
Running GPU Tests on the Github Actions CI

### ISSUE THREAD

**Issue by aktech** [pystatgen/sgkit#512]
## Problem
At the moment we don't have a way to run tests in sgkit on GPU, we will soon have some GPU tests after #498 is merged. It will be good idea to figure out something soon.

Github Actions doesn't provides a way to spin up GPU on its infrastructure as of now. The only way to run tests on GPU via Github Actions is via [self hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners).

## Solution I: Self-Hosted, Self-Managed
Self hosted runners is basically a way to make any machine as Github Actions machine, so how this will work is we create a GPU machine on a Cloud provider, let's say AWS and install the Github Actions runner application there and keep it running, that will listen to jobs on this repository and will execute GPU tests eventually.

### Problem with Solution I
The above approach works well, but there is one problem with it, the cheapest GPU machine, I found on AWS was the following:

```
g4dn.xlarge | 4 | N/A | 16 GiB | 125 GB NVMe SSD | $0.526 per Hour
```
Source: https://aws.amazon.com/ec2/pricing/on-demand/

This is **$0.526** per hour, so this will cost roughly ~ **0.526 x 24 x 30** = **$378.72 per month**

Another problem with it is when you create a self hosted machine, people can run code on it via PR and can kill the machine and then you have to set it up again, so there is some maintenance cost as well.

## Solution II: Cirun.io

I have been recently working on a solution to run Github Actions on your cloud provider to make the whole process easy, I recently released the service about couple of weeks ago: https://cirun.io/

Cirun lets you create ephemeral runners on the cloud of your choice (AWS and DigitalOcean at the moment). So how it works is you install the Cirun Application on the Github organization for a repository and add Cloud credentials to the Cirun. Now Cirun will listen to build events on the repository, when it receives the event it will create a machine (defined by the user) on the cloud provider and will kill the machine if its idle for more than 5 minutes.

This helps in two ways:

- Creates GPU machines on demand and kill them when not in use
- Create a new machine for a new job, so that if a machine is corrupted, we don't have to worry about setting up one manually.
- Cirun is free to use for open source projects.

To compare the costs, if we run GPU test for like 1 hour a day, it will cost us ~ **0.526 x 30** = $15.78 per month. 

Note: This suggestion might be biased, since I am the creator of Cirun.io and the upside is, I can help set this up.

cc @jeromekelleher @hammer

**Comment by jeromekelleher** [comment]
Thanks @aktech, this is very helpful.

**Comment by ravwojdyla** [comment]
#567 was merged, closing this. Note that it requires a follow up given #611.
