### ISSUE TITLE
Reading VCF with Chromosome Y

### ISSUE THREAD

**Issue by shy218** [pystatgen/sgkit#539]
I currently test the packages on a small vcf dataset, but the chromosome in the vcf file has Y, (I think it is a chromosome for sex?). However, sgkit function vcf_to_zarr() gives an error that "Y is not in list." Do I need to first convert Y into a number?

**Comment by tomwhite** [comment]
@shy218 you don't need to convert Y into a number, since chromosomes (contigs) are strings in general. Can you post the VCF file and code you are using to convert it please? (Also, I don't know if you've seen https://pystatgen.github.io/sgkit/latest/vcf.html which may be useful.)

**Comment by shy218** [comment]
Sorry. It is the problem with my testing file. I can't read it either by Hail or Plink. I use another VCF file provided by my friend, who works in a bioinformatics research lab, and it works. I currently use the VCF from here: https://ftp-trace.ncbi.nih.gov/1000genomes/ftp/release/20130502/
