### ISSUE TITLE
Incorporate documentation for IO repos

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#54]

**Comment by alimanfoo** [comment]
Hi @tomwhite, for the prototyping work I did on scikit-allel v2, I made a parent repo [skallel](https://github.com/scikit-allel/skallel) which has the sphinx documentation (published on [rtfd](https://skallel.readthedocs.io/en/latest/)), and it pulls in docstrings for two related repos, [skallel-tensor](https://github.com/scikit-allel/skallel-tensor) and [skallel-stats](https://github.com/scikit-allel/skallel-stats).

**Comment by tomwhite** [comment]
Thanks for the pointer @alimanfoo. There's a slight difference here because skallel has dependencies on skallel-tensor and skallel-stats, whereas sgkit does not have dependencies on sgkit-{bgen,plink,vcf}. Still, I think it's doable by installing the IO packages when building docs, see #235.

**Comment by tomwhite** [comment]
This was covered by #235
