### ISSUE TITLE
VCF file for alleles = 2

### ISSUE THREAD

**Issue by shy218** [pystatgen/sgkit#541]
I currently have the testing VCF file, but the number of alleles is 4. Do you have any dataset with alleles as 2? Or do we have functions, (like filter in Hail) to convert the alleles to 2 by deleting all the variants with alleles 4?

**Comment by eric-czech** [comment]
Hey @shy218, you could try [hail.methods.split_multi_hts](https://hail.is/docs/0.2/methods/genetics.html#hail.methods.split_multi_hts).  That would let you create a new VCF with only bi-allelic variants without losing any of the original variants.
