### ISSUE TITLE
Consider write path for IO libraries

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#544]
Over at https://github.com/malariagen/vector-data/discussions/22#discussioncomment-590949, @alimanfoo notes that Ag1000G only releases their data as VCF files, and that it might be nice to have the same data in a PLINK-accessible format. Could `sgkit` handle this conversion?

**Comment by alimanfoo** [comment]
Hi folks, just to mention that the ability to write data from sgkit-style xarray dataset to plink format has come up again as something that would be very useful to have.

Specific use case currently is wanting to run [ADMIXTURE](https://dalexander.github.io/admixture/) for which there is no Python implementation currently AFAIK.

**Comment by alimanfoo** [comment]
Just to add, a convenient workflow is to have data in zarr format, then use sgkit and xarray to select samples and variants to be used for the admixture analysis, then export this selection to plink.

**Comment by alimanfoo** [comment]
Looks like the bed-reader package has a [to_bed()](https://fastlmm.github.io/bed-reader/#bed_reader.to_bed) function.

**Comment by tomwhite** [comment]
Closing this as work on this is being tracked by #924 and #926.
