### ISSUE TITLE
Align pc_relate with pca results

### ISSUE THREAD

**Issue by ravwojdyla** [pystatgen/sgkit#554]
`pc_relate` came before our own implementation of `pca`, and it expects the PCs for samples to be `(components, samples)`. Our `pca` will produce `sample_pca_projection` that are `(samples, components)`, which requires a transpose to use in the context of the `pc_relate`.

TODO:
 * results of `pca` should be readily usable in the context of `pc_relate` 
 * now that we have our own `pca`, let's use it in the `pc_relate` tests instead of the `sklearn` one

**Comment by tomwhite** [comment]
Fixed in #587
