### ISSUE TITLE
Observed heterozygosity does not handle samples without a cohort.

### ISSUE THREAD

**Issue by timothymillar** [pystatgen/sgkit#566]
In `observed_heterozygosity` samples without are cohort are not being ignored correctly.

I missed the option of specifying a sample of not belonging to a cohort with -1 ([code](https://github.com/pystatgen/sgkit/blob/main/sgkit/stats/popgen.py#L954)). This should be handled as in `count_call_alleles` ([code](https://github.com/pystatgen/sgkit/blob/main/sgkit/stats/aggregation.py#L95)).

Side note: the `sample_cohort` variable is not specified in `sgkit/variables.py` or in the API documentation.

**Comment by tomwhite** [comment]
I've opened #570 to add documentation about cohorts.
