### ISSUE TITLE
Nightly conda-forge builds?

### ISSUE THREAD

**Issue by aktech** [pystatgen/sgkit#578]
We recently added sgkit to [conda-forge](https://anaconda.org/conda-forge/sgkit), which is great, but it will be great if we could upload nightly builds, just like Dask, Numba to be able to install the latest version as a user.

**Comment by jeromekelleher** [comment]
I'm reluctant to do this @aktech as it's a fair bit of complexity on the conda packaging side. Sophisticated users (those we'd want using nightly builds) can install the latest using pip from git, right?

**Comment by aktech** [comment]
OK, makes sense.

> Sophisticated users (those we'd want using nightly builds) can install the latest using pip from git, right?

Yep, that's what I do at the moment.
