### ISSUE TITLE
Use attrs?

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit#59]
Anyone object to us using [attrs](https://www.attrs.org/en/stable/)? It's a pretty standard dependency, and it does clean code up quite a lot by emphasising simple data classes. 

Alternatively, we could use [dataclasses](https://www.python.org/dev/peps/pep-0557/) from the std library. This would make our lowest version 3.7, which is actually not so bad (3.7 is the version of Python shipped in Debian stable, which is a good bar for what should be supported IMO).

**Comment by ravwojdyla** [comment]
+1 to dataclasses, which btw we already use [here](https://github.com/pystatgen/sgkit/blob/master/sgkit/stats/association.py#L13-L17).

**Comment by hammer** [comment]
+1 to dataclasses

**Comment by jeromekelleher** [comment]
OK, done, dataclasses it is.

**Comment by hammer** [comment]
It may be bad form to drop this link on a closed issue, but I came across https://github.com/abatilo/typed-json-dataclass and thought it looked interesting. @ravwojdyla have you ever evaluated it?

**Comment by ravwojdyla** [comment]
@hammer for that use case I have used [pydantic](https://github.com/samuelcolvin/pydantic), and that worked well and I definitely recommend it.

**Comment by hammer** [comment]
Ah yes, for some reason I had not included `pydantic` in my mental model for this task, but their [benchmarks page](https://pydantic-docs.helpmanual.io/benchmarks/) makes clear they are in the competitive set.

**Comment by ravwojdyla** [comment]
Yep, overall `pydantic` has been relatively good. I have used it as a data model for python ETLs mostly for typed BigQuery IO and JSON, plus some data generation, and yes I mostly have used it with dataclasses.
