### ISSUE TITLE
Change minimum Python version to 3.7

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit#60]
In setup.cfg we say Python 3.6 is supported, but 3.7 is really the minimum since we're using dataclasses (as discussed in #59). Update the minimum version to 3.7.

We could use the version of dataclasses from pypi, alternatively, and support 3.6, but since this is a new project going with 3.7 as a minimum seems reasonable (especially since sgkit-plink will only support 3.7+).

I'd imagine we could include 3.8 also, but I guess we should test this in CI.

**Comment by tomwhite** [comment]
+1

We should also change the GitHub Action to run on both Python 3.7. and 3.8 as a part of this. It currently runs on 3.8 only.
