### ISSUE TITLE
Dask "Ask a Maintainer" office hours for life sciences

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#600]
From Genevieve Buckley:

> Following on from the Dask Summit, we're introducing "Ask a Maintainer" office hours for people in life sciences. The first is with Ben Zaitlen at https://whereby.com/dask-dev on Wednesday June 9th [at this time](https://everytimezone.com/s/b0c638c2) (11am EDT / 8am PDT /  5pm CET). Click here to add the event to your calendar.
>
> We'll trial running them once every two weeks, at varying times (this lets us accommodate our maintainers schedules, and cater to different timezones). Please tell us what you like, don't like, or would like to see changed.

The first one is tomorrow (which unfortunately I can't go to due to a clash). There's a calendar on https://docs.dask.org/en/latest/support.html with a link to the event if you are interested in attending.

**Comment by hammer** [comment]
Okay if I move this to a discussion topic? We can add replies to that topic if we want to remind ourselves to send questions to them.

**Comment by hammer** [comment]
Moved to https://github.com/pystatgen/sgkit/discussions/601
