### ISSUE TITLE
CSV file descriptions for test_regenie results

### ISSUE THREAD

**Issue by gagank1** [pystatgen/sgkit#623]
The CSV files in sgkit/tests/test_regenie/result could benefit from file descriptions as some of the column names are not clear. @EpiSlim

**Comment by eric-czech** [comment]
Hey @gagank1, the `gwas.csv` fields have these interpretations:

- `names`: The variant ID 
- `label`: A simulated phenotype
- `beta`/`standardError`/`pValues`: Results from running glow linear regression after running glow's regenie transformation

Does that clear up any confusion?
