### ISSUE TITLE
Add IBS based kinship estimator of Weir and Goudet (2017)

### ISSUE THREAD

**Issue by timothymillar** [pystatgen/sgkit#635]
I have been using the kinship estimator developed by [Weir and Goudet (2017)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5560808/) ($\hat{\beta}_{jj'}^i$ in table 3) and have found it very accurate and convenient. This method is based on IBS probabilities and is particularly accurate when samples are closely related, e.g. samples from a single pedigree (see [Goudet, Kay and Weir 2018](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6220858/)). I already have a rough implementation in sgkit.

**Comment by eric-czech** [comment]
Nice!  Do you often need IBD estimates as well?  A method to compute either with some invariance to population structure would be awesome.  We added [pc_relate](https://pubmed.ncbi.nlm.nih.gov/26748516/) a while back, which could produce IBD sharing probabilities, but it requires PCs for population correction and those PCs ideally require sample independence (so we have a chicken and egg scenario).  

KING comes up most frequently as a solution for this problem -- do you know off the top of your head if this method is comparable?

**Comment by jeromekelleher** [comment]
This sounds like a great idea to me @timothymillar!

**Comment by timothymillar** [comment]
@eric-czech currently I'm using the W & G method to identify samples whose relationships don't match those expected based on pedigree (due to miss-sampling, rogue pollen etc.). This doesn't require a real IBD value, just something proportional to it. The W & G method calculates kinship relative to to the current (i.e. sampled) population which they refer to as "within population kinship" (analogous to F_IS). This means that the values identified can be negative (hence not actual IBD) with the non-diagonal (non-self) values summing to zero.

W & G also provide a method (eq. 11) to correct the above estimates based on the set of least related individuals. This can produce positive estimates that could be interpreted as IBD values. However, they point out that the resulting values are still relative to the sampled population (the least related samples could still be closely related/inbred). So the applicability of the corrected estimator probably depends on the population and hypothesis in question.

Thanks for pointing out the KING method, I'm not familiar with it but I'll look into it. W & G describe the KING-robust method as "estimating ibd between individuals relative to that within individuals".

**Comment by eric-czech** [comment]
Thanks @timothymillar, good to know and still sounds promising (I think).  I only know the KING methods well enough to know they're not particularly easy to implement and are very common as early stage QC filters in human genetics pipelines.  

Perhaps it will make sense at some later point to implement eq. 11 based on your IBS code and compare to KING on the same data.

**Comment by timothymillar** [comment]
Done in #647
