### ISSUE TITLE
Data reading time in benchmark

### ISSUE THREAD

**Issue by LiangdeLI** [pystatgen/sgkit#636]
Should data reading time be included in benchmark of sgkit and hail? 

I have done some benchmark of allele frequency, (variant_stats() for sgkit, --freq for plink, variant_qc() for hail), leading to some thoughts on this question:

1.Because each plink command line operates on data directly (i.e. --file data_file), it seems fair to include sgkit's and hail's data reading time as well to compare.
2.Because of using .vcf file data, sgkit has to convert to zarr first, then read it. In my experience, this 'vcf_to_zarr' function can take significant time. The other two tools can directly operate/create datasets on .vcf.

Thus I'm thinking of including data reading time in benchmark, but reading in each tool's preferred format, i.e. .bed for plink, .mt for hail and zarr for sgkit. What's your suggestion?

One more thing: Do you have a plan to implement something like: vcf_to_dataset? Or there is one already? 

Please correct me if I missed anything.

**Comment by tomwhite** [comment]
> Thus I'm thinking of including data reading time in benchmark, but reading in each tool's preferred format, i.e. .bed for plink, .mt for hail and zarr for sgkit.

I agree with this.

> Do you have a plan to implement something like: vcf_to_dataset?

It doesn't exist, but we could add `read_vcf` (by analogy with `read_bgen` and `read_plink`), which did the conversion to Zarr, then opened as a dataset.
