### ISSUE TITLE
Use of int8 for call_genotype results in integer overflow with complex variants

### ISSUE THREAD

**Issue by timothymillar** [pystatgen/sgkit#640]
I'm working with some microhaplotype variant calls in which the number of the alleles can be >300 (likely due to poor quality calls at some loci). It would be ideal if the `call_genotype` dtype was configurable and/or automatically set based on the `max_alt_alleles` parameter. Similar discussion in #584.

**Comment by jeromekelleher** [comment]
+1 - this is definitely an issue. Setting based on max_alt_alleles is good, and I think that seals the deal on mapping any alleles we can't represent to missing data.

**Comment by tomwhite** [comment]
> It would be ideal if the `call_genotype` dtype was configurable and/or automatically set based on the `max_alt_alleles` parameter.

+1

BTW I just opened #643, which is tangentially related. @timothymillar I wonder if you see a few very long alleles in your data?

**Comment by timothymillar** [comment]
> I wonder if you see a few very long alleles in your data

I'm currently working with alleles with lengths 120bp. These are fixed sized "chunks" across the genome (targeted sequencing) so fixed length strings are suitable. But I think we'll use more variable allele lengths in future as these chunks need some tuning. 
We also use freebayes quite regularly which can produce highly variable allele lengths. However, most of the data I'm working with is targeted sequencing so the datasets are quite small in the variants dimension.

**Comment by tomwhite** [comment]
Good to know - thanks.
