### ISSUE TITLE
Use PackBits filter for boolean fields for Zarr storage

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#642]
When writing Zarr files we should enable the [PackBits](https://numcodecs.readthedocs.io/en/stable/packbits.html) filter for boolean fields.

For some 1000 genomes data I saw `call_genotype_phased` go from 2.8 MB to 212 K, after enabling it.

**Comment by jeromekelleher** [comment]
Nice! I guess we should provide fairly open access to the Zarr compressors and filters too - it's good to be able to fiddle with these for specific applications.

**Comment by tomwhite** [comment]
Fixed in #644
