### ISSUE TITLE
Presentation for GA4GH "Future of VCF" meeting

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#646]
I'm giving a short presentation about our use of Zarr for storing variant data at the next GA4GH "Future of VCF" meeting (9 August). Here are my draft slides for general interest and if anyone has any feedback:

[VCF and Zarr.pdf](https://github.com/pystatgen/sgkit/files/6925628/VCF.and.Zarr.pdf)

(BTW The benchmarks section will hopefully be updated with some numbers from simulations that @jeromekelleher is currently running.)

**Comment by jeromekelleher** [comment]
Looks great @tomwhite - I'll post a plot here when I get the numbers for the simulations I'm running.

**Comment by tomwhite** [comment]
Minutes, with linked slides and Jerome's simulations, are here: https://docs.google.com/document/d/1OKFeHJLXoCwWybQHOsVnIG0VDtP-EaAgLUIgFzwQckQ/edit#
