### ISSUE TITLE
make html fails without dot

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#666]
When I run `make html` in `docs/` on a clean checkout, I get an exception that seems to be caused by the calls to `counts.visualize` in [user_guide.rst](https://github.com/pystatgen/sgkit/blob/main/docs/user_guide.rst) which require the Graphviz `dot` executable.

It's easy to fix locally (on Mac, `brew install graphviz`), but we should either update our "Contributing to documentation" docs or remove these calls.

Which solution do people prefer?

**Comment by jeromekelleher** [comment]
I guess visualising task graphs is going to be a fairly common thing we want to do in the docs, so probably best to make graphviz a dev requirement?

**Comment by tomwhite** [comment]
+1 to making graphviz a dev requirement.

**Comment by hammer** [comment]
Note that we can make the PyPI package `graphviz` a dev requirement but that does not address this issue.

The issue here is that there does not appear to be a way to add the `dot` executable required by the `graphviz` Python library to our dependencies and thus we will require a manual installation step for users. It seems like we just have to point users to https://graphviz.org/download/#executable-packages to get `dot`.

**Comment by jeromekelleher** [comment]
I guess telling devs they need to install graphviz (e.g. ``apt install graphviz``) is the best solution. It's widely known, so I don't think it'll throw too many people.

**Comment by hammer** [comment]
Random thought: how are our GH Actions doc builds succeeding? Are we installing `dot` there too?

**Comment by tomwhite** [comment]
> Random thought: how are our GH Actions doc builds succeeding? Are we installing `dot` there too?

Yes, see e.g. https://github.com/pystatgen/sgkit/blob/e2cfc7aa5de60452f75915ba0537c06c6223e434/.github/workflows/build.yml#L28
