### ISSUE TITLE
Remove `xarray_internal` concat algorithm in VCF reader

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#678]
As discussed in #665, `concat_algorithm="xarray_internal"` has scaling issues, and doesn't handle variable-length strings well, so we can drop it to simplify the code.

**Comment by hammer** [comment]
@tomwhite could you link to the upstream issue for the scaling issues here? 🙏

**Comment by tomwhite** [comment]
The Dask issue is https://github.com/dask/dask/issues/6745. It's now closed, although the problem hasn't been fixed.

**Comment by tomwhite** [comment]
I should add that fixing this would avoid another problem we have been having with Xarray: https://github.com/pydata/xarray/discussions/5769
