### ISSUE TITLE
Add a blog

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#682]
https://predictablynoisy.com/posts/2020/sphinx-blogging has useful links

**Comment by hammer** [comment]
There's some additional configuration that we'll need for RSS feeds, etc. but the below works for me.

0. `pip install ablog`
1. Add `"ablog"` to the `extensions` array in `conf.py`.
2. Add `blog` to the end of the `toctree` in `index.rst`.
3. Add `blog.rst`:
```
.. _blog:

**********
sgkit Blog
**********

.. postlist:: 10
   :date: %Y-%m-%d
   :format: {date} - {title}
   :list-style: none
   :excerpts:
```
4. Make the `blog` dir and change into it.
5. Add `firstpost.rst`:
```
First post
==========

.. post:: 19 September 2021
    :tags: genetics
    :category: Releases
    :author: hammer

There should be some text here.
```

**Comment by jeromekelleher** [comment]
Any chance we can do this with Markdown? Or is it not worth fiddling with? (I thought we were using MyST Markdown elsewhere in the docs build?)

**Comment by hammer** [comment]
Some good points on why MyST is not quite ready for prime time at https://github.com/dask/dask-gateway/issues/427

**Comment by jeromekelleher** [comment]
Yeah, it's not perfect. FWIW we've ended up with a mixture of rST for docstrings and MyST for the larger documentation in msprime. Works well enough, and using MyST felt a lot nicer for writing prose.

**Comment by hammer** [comment]
Alternatively we can skip the `post` directive and use the `blog_post_pattern` configuration setting that Chris uses for his blog. The directive feels more explicit to me though?

**Comment by jeromekelleher** [comment]
I don't have an opinion - whatever you think.

**Comment by eric-czech** [comment]
FYI the team at Nvidia (cc: @EpiSlim, @quasiben, @pentschev, and Harry) is going to write a blog post discussing regenie/dask/cupy and include some introductory material on sgkit.  @jeromekelleher / @tomwhite / @hammer did any of you ever start on drafts or outlines for the first blog post we were discussing here?  I'm also wondering if it's worth engaging NumFOCUS to get some wider distribution once it's ready.

**Comment by jeromekelleher** [comment]
Nope, I haven't done anything. Definition +1 on engaging NumFOCUS!

**Comment by hammer** [comment]
I was supposed to do it but haven’t gotten around to it. If someone else wants to do it, that would be great.
