### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#7]
- GitHub [code of conduct docs](https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project)
- [PSF code of conduct](https://www.python.org/psf/conduct/)
- [NumFOCUS code of conduct](https://numfocus.org/code-of-conduct)
- [Dask code of conduct](https://github.com/dask/governance/blob/master/code-of-conduct.md)

Given that we don't host events we should extract the sections relevant to online communities.

**Comment by jeromekelleher** [comment]
The [contributor covenant](https://www.contributor-covenant.org/) is one of the templates available on GitHub. Unless there's compelling reason to use something else, I suggest using it.

It's probably a good idea to setup a [``.github`` repo](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file)  to hold this community health info.

**Comment by tomwhite** [comment]
+1 to using the GitHub contributor covenant.

**Comment by tomwhite** [comment]
I've created the [.github repo](https://github.com/pystatgen/.github).

The contributor convenant doc needs an email address for escalation. Any suggestions about which one(s) to add? Perhaps one from Related Sciences and one from Oxford BDI.

**Comment by jeromekelleher** [comment]
Alternatively, we could define a generic project admin email address that gets forwarded on to a few key people. That way we don't have to worry about the email addresses going out of date. It's also handy to have a generic project email for things like the PyPI package, etc.

This would involve registering a domain, though. Something like pystatgen.org/.dev/...?

**Comment by hammer** [comment]
The only issue with registering `pystatgen.org` is that we have previously discussed migrating to `pydata-statgen` for our org name once we are affiliated with NumFOCUS. I can see the advantage of using the shorter version, though, so if sentiments have changed I could be convinced to just go forward with`pystatgen`.

The other path forward is to register `sgkit.org`.

**Comment by jeromekelleher** [comment]
I don't have any real opinions on the domain name - I don't think it matters a huge amount once it's something vaguely related to the project.

**Comment by hammer** [comment]
I need to get us an email!

**Comment by hammer** [comment]
Okay I bought the `pystatgen.org` domain used a 1-user (`admin@pystatgen.org`) G Suite Basic subscription to set up a Google Group at `project@pystatgen.org` with me and @jeromekelleher as members. I don't know if that was the best way to get us a group email address, but it's what we have now!

**Comment by hammer** [comment]
Also, I'm taking myself off this issue now that my part is done. For those that know what code of conduct we want to use and how to use it, please pick it up from here... 🙏
