### ISSUE TITLE
Annotated types in docstrings

### ISSUE THREAD

**Issue by eric-czech** [pystatgen/sgkit#72]
I have been duplicating type information in docstrings like this:

```python
def fn(x: List[int]) -> None:
  """Some function.

  Parameters
  ------------
  x : List[int]
    Some parameters
```

I've been doing that because it seems to be the standard numpydoc approach (and VSCode does it for me) but perhaps we want to do something else.  @ravwojdyla suggested not copying it there, possibly in favor of only adding more informative information like array dimensions when applicable.

**Comment by tomwhite** [comment]
This was fixed in #261
