### ISSUE TITLE
Remove use of NumPy 1.21 features

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#726]
We currently require NumPy 1.21 due to our use of [`numpy.typing.NDArray`](https://numpy.org/devdocs/reference/typing.html#numpy.typing.NDArray) which was introduced in that version.

However, we also [exclude Numba 0.54.0 since](https://github.com/pystatgen/sgkit/blob/main/setup.cfg#L36) it is not compatible with NumPy 1.21.

#656 was an attempt to fix this, but in practice conda installs a version of NumPy < 1.21, which doesn't have `NDArray`, which then causes the sgkit import to fail. (Pip installation works ok, which is why this is not failing on CI.)

I think we should roll back our use of `numpy.typing.NDArray` so we can use earlier NumPy versions without issue.

Found while working on #725

**Comment by jeromekelleher** [comment]
Agreed - type annotations are "nice-to-have" in my book

**Comment by pentschev** [comment]
Yes, that is fine for us, thanks for confirming @tomwhite !
