### ISSUE TITLE
PBS API

### ISSUE THREAD

**Issue by daletovar** [pystatgen/sgkit#73]
I wanted to spark some discussion on what the api for doing pbs should look like. Based on this [notebook](https://github.com/pystatgen/sgkit-requirements/blob/master/stories/gwss-pbs/gwss-pbs.ipynb) that @alimanfoo made, it looks like we'll need to implement something like this:
1. an allele count for each population.
    - sgkit.count_alleles will do this.
2. locate and subset to segregating variants at sufficient frequency.
    - requires an is_biallelic_01 function, or something equivalent.
    - requires a to_frequencies function, or some equivalent operation.
3. setup windows over the genome.
    - requires a moving_statistic function.
4. calculate the PBS in a moving window.
    - requires a pbs function.

**Comment by jeromekelleher** [comment]
Closing in favour of #230.
