### ISSUE TITLE
VCF Zarr specification

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#740]
Write a spec for how we represent VCF in Zarr. This is likely to be slightly different from the current sgkit implementation (field names should match the VCF field names, for example), but it should be easy to do a lightweight conversion to sgkit conventions via a utility method.

**Comment by jeromekelleher** [comment]
Totally agree.

I'm not sure there's much value in having a second zarr format with difference column names though - wouldn't it be simpler to just say "this column corresponds to VCF field X"? Either that or we just use the VCF names directly in the sgkit format, perhaps making the current names available as synonyms in sgkit?

**Comment by tomwhite** [comment]
I've updated the draft spec at https://github.com/tomwhite/sgkit/blob/vcfzarr-spec/vcf_zarr_spec.md following discussion on #755 to simplify the types and to remove the 32-bit limitation.

**Comment by tomwhite** [comment]
Another update of the draft spec, https://github.com/tomwhite/sgkit/blob/vcfzarr-spec/vcf_zarr_spec.md, which uses the column names we already have in sgkit (to reflect earlier comments in this issue).

**Comment by tomwhite** [comment]
I've created a repo for the spec at https://github.com/pystatgen/vcf-zarr-spec (as we discussed in the last meeting, #761), and a PR for the first version of the spec at https://github.com/pystatgen/vcf-zarr-spec/pull/1.

**Comment by tomwhite** [comment]
Fixed in https://github.com/pystatgen/vcf-zarr-spec/pull/1
