### ISSUE TITLE
Data structures documentation figure mentions "populations" but doesn't make a link to SGkit cohorts

### ISSUE THREAD

**Issue by hyanwong** [pystatgen/sgkit#767]
The illustrative image at https://pystatgen.github.io/sgkit/latest/getting_started.html#data-structures has a row labelled "population", but this is not mentioned later on in that section, so it is not immediately obvious that this would be encoded in SGkit using cohorts. A note in this section of the docs might be useful for newbies.

**Comment by tomwhite** [comment]
Thanks for reporting this @hyanwong. I think that diagram was created before we started using the term "cohort", but I agree that we should make the link between the two terms.

@eric-czech are you able to update the figure (or share a copy of it somewhere)?

**Comment by eric-czech** [comment]
It's at https://docs.google.com/drawings/d/1NheB6LCvvkB4C0nAoSFwoYVZ3mtOPaseGmg_mZvcQ8I if you want to copy + modify beyond changing population to cohort (which I just did).

**Comment by tomwhite** [comment]
Thanks @eric-czech!
