### ISSUE TITLE
Rename `call_genotype_non_allele` to `call_genotype_fill`?

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#772]
For consistency with a general way of specifying fill masks (https://github.com/pystatgen/vcf-zarr-spec/blob/main/vcf_zarr_spec.md#missing-and-fill-values) we might rename this variable. We could keep the "non-allele" terminology in the documentation in addition to describing it as a fill value.

Thoughts @timothymillar?

**Comment by timothymillar** [comment]
Sounds good @tomwhite. I think "fill" is more intuitive and could probably be used in the documentation as well.

**Comment by jeromekelleher** [comment]
SGTM also
