### ISSUE TITLE
Issue of vcf_to_zarr()'s .zarr output

### ISSUE THREAD

**Issue by LiangdeLI** [pystatgen/sgkit#785]
The .zarr output of `vcf_to_zarr()` is smaller than before in terms of size, like for a 201MB 1000 Genomes chromosome 21 vcf file, the new result is 50MB zarr file while it was 321MB before. However, I found some problems of this new compressed version of .zarr.

For example, if I simply run the following reading data and write:
```
ds = sg.load_dataset("/mydata/chr21.zarr")
ds[['variant_id']].to_zarr("/mydata/output.zarr", compute=True)
```
It works for the old 321MB version, but the new 50MB version would raise error:
```
/users/Liangde/.local/lib/python3.8/site-packages/xarray/conventions.py:201: SerializationWarning: variable None has data in the form of a dask array with dtype=object, which means it is being loaded into memory to determine a data type that can be safely stored on disk. To avoid this, coerce this variable to a fixed-size dtype with astype() before saving it.
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/Liangde/.local/lib/python3.8/site-packages/xarray/core/dataset.py", line 2031, in to_zarr
    return to_zarr(
  File "/users/Liangde/.local/lib/python3.8/site-packages/xarray/backends/api.py", line 1414, in to_zarr
    dump_to_store(dataset, zstore, writer, encoding=encoding)
  File "/users/Liangde/.local/lib/python3.8/site-packages/xarray/backends/api.py", line 1124, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/users/Liangde/.local/lib/python3.8/site-packages/xarray/backends/zarr.py", line 555, in store
    self.set_variables(
  File "/users/Liangde/.local/lib/python3.8/site-packages/xarray/backends/zarr.py", line 634, in set_variables
    writer.add(v.data, zarr_array, region)
  File "/users/Liangde/.local/lib/python3.8/site-packages/xarray/backends/common.py", line 155, in add
    target[region] = source
  File "/users/Liangde/.local/lib/python3.8/site-packages/zarr/core.py", line 1213, in __setitem__
    self.set_basic_selection(selection, value, fields=fields)
  File "/users/Liangde/.local/lib/python3.8/site-packages/zarr/core.py", line 1308, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/users/Liangde/.local/lib/python3.8/site-packages/zarr/core.py", line 1599, in _set_basic_selection_nd
    self._set_selection(indexer, value, fields=fields)
  File "/users/Liangde/.local/lib/python3.8/site-packages/zarr/core.py", line 1651, in _set_selection
    self._chunk_setitem(chunk_coords, chunk_selection, chunk_value, fields=fields)
  File "/users/Liangde/.local/lib/python3.8/site-packages/zarr/core.py", line 1888, in _chunk_setitem
    self._chunk_setitem_nosync(chunk_coords, chunk_selection, value,
  File "/users/Liangde/.local/lib/python3.8/site-packages/zarr/core.py", line 1893, in _chunk_setitem_nosync
    cdata = self._process_for_setitem(ckey, chunk_selection, value, fields=fields)
  File "/users/Liangde/.local/lib/python3.8/site-packages/zarr/core.py", line 1952, in _process_for_setitem
    return self._encode_chunk(chunk)
  File "/users/Liangde/.local/lib/python3.8/site-packages/zarr/core.py", line 2001, in _encode_chunk
    chunk = f.encode(chunk)
  File "numcodecs/vlen.pyx", line 106, in numcodecs.vlen.VLenUTF8.encode
TypeError: expected unicode string, found 16
```

**Comment by percyfal** [comment]
I have encountered this situation as well in a case where I read a vcf, convert to zarr, load the zarr dataset to perform some operations (ld pruning in this case), and then try to save which throws the error above. I did manage to identify a solution which I post here for reference. I'm pretty new to the xarray data structures so let me know if this makes sense or not.

Upon reading the zarr dataset (converted from vcf), the dtype of the Dataset Dataarrays 'variant_id', 'variant_allele' and 'sample_id' are 'O'; converting these to e.g. dtype=str does the trick. Apparently `sgkit.io.vcf.vcf_to_zarr` sets dtype="O" on these Dataarray objects which somehow causes problems for xarray encoding.

An alternative solution is to note that `vcf_to_zarr` sets the encoding in an elaborate way; printing this encoding and using it with `sgkit.save_dataset` also works. 

I'm unsure whether resetting the dtype is the proper solution, but I note that when simulating a dataset with `sgkit.simulate_genotype_call_dataset` the dtypes are `|S1` for 'variant_allele' and `<U4` for 'sample_id'.

**Comment by jeromekelleher** [comment]
Thanks for digging in here @percyfal. Numpy strings are always a pain :cry: 

Any thoughts here on what's going on @tomwhite?

**Comment by percyfal** [comment]
No problem @jeromekelleher I have some more info if needed. For some reason the encoding is given two passes in zarr.core.Array._encode_chunk:
```python
def _encode_chunk(self, chunk):
    # apply filters
    if self._filters:
        for f in self._filters:
            chunk = f.encode(chunk)
```
such that `chunk` is of type `bytearray` the second time around.

**Comment by tomwhite** [comment]
I agree that strings are hard to get right with NumPy - adding Zarr and Xarray makes things even more constrained.

In general, the approach we take is to store strings with dtype `O` and [Zarr's numcodecs.VLenUTF8 encoding for variable-length strings](https://zarr.readthedocs.io/en/stable/tutorial.html#string-arrays). See #665 and https://github.com/pystatgen/sgkit/blob/f39e1b1bc3b16d05c5043ab5d445076424dad229/sgkit/io/vcfzarr_reader.py#L360-L362

#643 and https://github.com/pydata/xarray/discussions/5769 are related too.

> An alternative solution is to note that `vcf_to_zarr` sets the encoding in an elaborate way; printing this encoding and using it with `sgkit.save_dataset` also works.

Perhaps we could make this easier to do, or automate it somehow?

**Comment by tomwhite** [comment]
@percyfal that looks like a decent approach to get things working. I'd like to understand this better though, as your original code should work as-is, and the fact that it doesn't looks like a bug to me. Are you able to share the VCF or extract a cutdown/anonymised version as a minimal reproducible example?

**Comment by percyfal** [comment]
The input VCF is actually simulated using [stdpopsim](https://popsim-consortium.github.io/stdpopsim-docs/stable/index.html) and [tskit](https://tskit.dev/tskit/docs/stable/introduction.html):
```shell
stdpopsim HomSap -d OutOfAfrica_3G09 -c chr21  -o ooa.chr21.ts -l 0.1 -s 42 10 10 10
tskit vcf --ploidy 2 ooa.chr21.ts | sed -e "s/contig=<ID=1/contig=<ID=chr21/g" | sed -e "s/^1/chr21/g" |  bcftools view -O z -o ooa.chr21.vcf.gz
```
A MWE in python is then
```python
import sgkit as sg
import sgkit.io.vcf as sgvcf
sgvcf.vcf_to_zarr("ooa.chr21.vcf.gz", "ooa.chr21.vcf.gz.zarr")
ds = sg.load_dataset("ooa.chr21.vcf.gz.zarr")
sg.save_dataset(ds, "foo.zarr", mode="w")
```
which fails with the error above. The simulated output encodes ref/alt as 0/1, which e.g. gatk ValidateVariants complains about. I tried the code also on a "regular" vcf, with the same error.

**Comment by tomwhite** [comment]
Thanks for the MWE @percyfal! I have been trying to get to the bottom of this, and I think there are at least two issues. (The ref/alt 0/1 encoding is not the problem, as you point out, since the same thing happens with any VCF.)

The root cause seems to be this long-standing issue in xarray: https://github.com/pydata/xarray/issues/3476. I think we can solve this in `sgkit.save_dataset`, see https://github.com/tomwhite/sgkit/tree/save-dataset-double-encoding-fix for a fix. (Does this work for you?)

The warning is still a problem though, and I'm not sure how to fix it yet. The warning is coming from xarray:

```
xarray.coding.variables.SerializationWarning: variable None has data in the form of a dask array with dtype=object, which means it is being loaded into memory to determine a data type that can be safely stored on disk. To avoid this, coerce this variable to a fixed-size dtype with astype() before saving it.
```

We don't get this warning in the initial `vcf_to_zarr` code since the arrays are not Dask arrays. However, when we load a dataset, the arrays are Dask arrays, so we get the warning. I opened [this issue](https://github.com/pydata/xarray/discussions/5769) a while back, but still don't have a good workaround or fix. Since it is a warning, it shouldn't stop you as long as you are not working with very large datasets.

**Comment by percyfal** [comment]
@tomwhite your proposed fix solves my problem, thanks, and presumably the originally posted issue.

Cheers,

Per

**Comment by tomwhite** [comment]
Great - thanks for trying it out.

**Comment by hammer** [comment]
Great detective work @tomwhite! Should we file an issue to track the upstream Xarray + Zarr issue?

**Comment by tomwhite** [comment]
Yes, I opened #853 for the remaining problem.
