### ISSUE TITLE
Can't make equally spaced overlapping windows

### ISSUE THREAD

**Issue by timothymillar** [pystatgen/sgkit#790]
I can't seem to do this with `window_by_position`. 

I looks like the  `window_start_position` argument implicitly expects the specified positions match the contigs of the `variant_contig` array. The contig bounds are calculated [here](https://github.com/pystatgen/sgkit/blob/main/sgkit/window.py#L229) from the `variant_contig` array. The bounds of a given contig (start and stop) are the indices corresponding to the first and last variants on the contig. These bounds are then used [here](https://github.com/pystatgen/sgkit/blob/main/sgkit/window.py#L291) to slice the provided `window_start_positions` and therefore assume that `window_start_positions` match the contigs of `variant_contig`. This assumption is true if  you use `window_start_positions=variant_position` but unlikely to be true for a custom array.

There doesn't seem to be a way to make overlapping windows without using the  `window_start_position` argument.

**Comment by tomwhite** [comment]
You are right @timothymillar - in the current implementation `window_start_position` has to be of size `variants`. This could be made more flexible though and probably should be to accommodate your use case. (Another generalisation that would be useful would be to have `window_stop_positions` to make it possible to define any number of variable-sized windows.)

Is this something you could look at implementing? I have less time this year on sgkit, so can't promise how soon I could get to it, but would be happy to review.

**Comment by timothymillar** [comment]
Thanks @tomwhite. I'm currently quite busy with my thesis but I can have a look when I have some time. It's fairly straightforward to generate overlapping windows on an an ad-hoc basis anyway.

Yes, window_stop_positions would be useful to generate windows from BED/GFF files.

**Comment by tomwhite** [comment]
Thinking about this more, this case can easily be supported by added a `step` argument (like the one in `window_by_variant`). See #793. How does this look @timothymillar?

**Comment by timothymillar** [comment]
That looks great, thanks @tomwhite !
