### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by hammer** [pystatgen/sgkit#8]
No rush; we need to formulate them first!

- [GitHub contributing guidelines documentation](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors)

**Comment by jeromekelleher** [comment]
Similar to #7, I suggest adding this to the ``.github`` repo.

**Comment by tomwhite** [comment]
[Dask](https://docs.dask.org/en/latest/develop.html), [Xarray](http://xarray.pydata.org/en/stable/contributing.html), and [Zarr](https://zarr.readthedocs.io/en/stable/contributing.html) all have contributing guidleines in their published documentation, linked to from a CONTRIBUTING.md file. Should we do the same?
