### ISSUE TITLE
Remove support for Python 3.7

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#802]
[NumPy 1.22](https://numpy.org/devdocs/release/1.22.0-notes.html) no longer supports Python 3.7, so we should consider removing support for it in the next release of sgkit.

This would be consistent with https://numpy.org/neps/nep-0029-deprecation_policy.html, which says Python 3.7 can be dropped from Dec 26, 2021.

**Comment by jeromekelleher** [comment]
Seems quite early to drop 3.7 tbh - is there much to be gained? To me there aren't any standout features in 3.8 making it worthwhile, and we're unlikely to (shouldn't?) depend on features required numpy 1.22 for a long time.

I don't feel strongly about it, though.

**Comment by tomwhite** [comment]
No particular rush, just wanted to open it for discussion. Installing Python 3.8 envs using conda is easy enough on most platforms so I suspect that shouldn't be a blocker.

**Comment by tomwhite** [comment]
Well that was quick. Our [upstream tests just failed](https://github.com/pystatgen/sgkit/runs/4843974784?check_suite_focus=true) because xarray has already [dropped Python 3.7](https://github.com/pydata/xarray/issues/6138).

**Comment by tomwhite** [comment]
[Pandas 1.4.0](https://pandas.pydata.org/docs/dev/whatsnew/v1.4.0.html#increased-minimum-version-for-python) does not support Python 3.7.

**Comment by tomwhite** [comment]
The build is now failing on Python 3.7 (https://github.com/pystatgen/sgkit/actions/runs/3186604485), so I'm thinking it's probably time to remove support for it.
