### ISSUE TITLE
Upstream failing due to numpy/numba conflict

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#809]
With `numpy==1.22.1` and `numba==0.55.0` we get `ImportError: Numba needs NumPy 1.21 or less`.

This is not happening on the main build because another dependency is specifying a lower numpy version (I think).

**Comment by ravwojdyla** [comment]
@tomwhite Validation Suite is also failing for the same reason https://github.com/pystatgen/sgkit/actions/runs/1721056036

**Comment by jeromekelleher** [comment]
Oddly enough the code that's throwing this error isn't in the current [git version](https://github.com/numba/numba/blob/ef1ba4c10b753ca31e9d4ff3de874d85be1be9c2/numba/__init__.py#L130), but it looks like they are keeping support for Python 3.7. 

I'm not sure whey they stopped putting the cap on numpy maximum version.

**Comment by jeromekelleher** [comment]
Probably simplest for us to have numpy < 1.22 for now and to keep Python 3.7, until other stuff starts breaking?
