### ISSUE TITLE
Investigate upgrading rechunker

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#820]
We are pinned to rechunker 0.3.3 due to this issues: https://github.com/pangeo-data/rechunker/issues/92.

However, the latest version of Dask (2022.01.1) doesn't work with rechunker 0.3.3 (see #819).

We should work out how to make progress here.

**Comment by rabernat** [comment]
Tom I'm sorry for the friction this is causing you. We need to do some serious work on rechunker to fix the performance problem introduced in 0.4. Hopefully we can get to that very soon.

How do you know rechunker doesn't work with dask 2022.01.1. Could you open an issue for that in rechunker?

**Comment by tomwhite** [comment]
Thanks Ryan! It would be great to get to the bottom of what is happening in rechunker 0.4 so it can be fixed.

I will open an issue in rechunker about the dask problem.

**Comment by tomwhite** [comment]
@eric-czech do you remember what caused us to pin rechunker to 0.3.3? We use it directly in the bgen reader, so I wonder if it was when you were working with biobank data? It would be great if we could verify that we can upgrade rechunker with the new fix in main, but I don't have an sgkit test case to check it with.

**Comment by eric-czech** [comment]
> @eric-czech do you remember what caused us to pin rechunker to 0.3.3?

Hm I don't and I'm pretty sure the last version I ever tested at scale on bgen data was 0.3.1 (I was using this [environment](https://github.com/related-sciences/ukb-gwas-pipeline-nealelab/blob/231d0e6e74772d1ae56205723952a5fff955aa74/envs/gwas.yaml#L32)).  I could be wrong, but I don't recall adding a pin in sgkit for any particular reason.

**Comment by eric-czech** [comment]
> I don't have an sgkit test case to check it with

You're worried the current rechunking test cases for bgen_reader don't cover potential issues at a larger scale?

**Comment by tomwhite** [comment]
Thanks @eric-czech!

> You're worried the current rechunking test cases for bgen_reader don't cover potential issues at a larger scale?

Yes. In yesterday's meeting we decided to upgrade to the new rechunker (0.5.0), and fix any scalability problems if they arise.

**Comment by rabernat** [comment]
I'm eager to hear whether 0.5 works for you. It's hard to cover very large computations with CI, but in all of my ad hoc testing, the scalability problems from 0.4 have disappeared.

**Comment by eric-czech** [comment]
> You're worried the current rechunking test cases for bgen_reader don't cover potential issues at a larger scale?
>> Yes. In yesterday's meeting we decided to upgrade to the new rechunker (0.5.0), and fix any scalability problems if they arise.

Got it.  The best way I can think to test then (since I can't share the files) is probably to write a big fake bgen file with https://github.com/lemieuxl/pybgen and then try the sgkit rechunker on it.  That was what I used to when I was experimenting on smaller, synthetic bgen data.  If you could get it to create dask arrays with roughly square chunks, then that would be all I was trying to accomplish in the beginning.
