### ISSUE TITLE
Pedigree topological order

### ISSUE THREAD

**Issue by timothymillar** [pystatgen/sgkit#844]
Many pedigree algorithms require the topological ordering of nodes such that each individual occurs before its decedents. In sgkit it makes sense to simply calculate and store the topological order as an array of indices. This array can be calculated from the `parent` array introduced in #839. There are several graph libraries which could be used to compute topological order https://github.com/pystatgen/sgkit/discussions/786#discussioncomment-1863520. Alternatively we could implement [Kahn's algorithm](https://en.wikipedia.org/wiki/Topological_sorting) to avoid picking up another dependency (it's quite simple).

Either way the API is quite simple e.g. `topological_sort(ds, parent=parent)` -> `ds` with `topological_order` where  `topological_order` has dimension `samples` and is of type `uint64`. Suggestions for better names are welcome!

**Comment by jeromekelleher** [comment]
Great idea @timothymillar. I suspect it would be simpler to just implement this ourselves. We have an implementation in tskit we can compare against: 
- https://tskit.dev/tskit/docs/stable/python-api.html#tskit.TableCollection.sort_individuals 
- [C code](https://github.com/tskit-dev/tskit/blob/3376ebf8b8ea7ddc5e95c3a54dcfba3e727a1557/c/tskit/tables.c#L6755)

**Comment by timothymillar** [comment]
Just a question on implementation details @jeromekelleher. In my mind a pedigree is a collection of vertices and edges with direction `parent --> child`, however, in the `parent` array we are storing those edges as `child --> parent`. Therefore, it's simpler to compute a topological order assuming `child --> parent` direction (as in Tskit). We can then reverse the computed topological ordering to get back to the intended `parent --> child` ordering. Does this make sense to you or would you prefer storing the `child --> parent` ordering?

**Comment by timothymillar** [comment]
Looking into this further I don't think that storing the topological sort order is the correct way to go. The problem is that storing the sort order in a Dataset requires that we give it a dimention. The obvious dimension choice is "samples" as there is one value per sample, however, this would imply that the i<sup>th</sup> value in the sort order array relates to the i<sup>th</sup> sample in the Dataset. This is not the case because these values indicate a different sample ordering. 

An alternative would be to store the *position* of each sample within the topological order (`position = np.argsort(order)`). In this case the i<sup>th</sup> value does relate to the i<sup>th</sup> individual (its position in the new order). The positions can be transformed back into the order with `order= np.argsort(position)`. I don't like this solution though as switching between the order and position is bound to cause confusion.

My current implementation of topological sort (based on the Tskit implementation) is fast enough that I don't think that there's justification for storing the order. Instead we can just compute the order on the fly when needed. I'm currently getting around 2.9 ms for a random pedigree of 100,000 samples with 10 founders. This is less than half the time it takes to run `np.argsort` on the result (although that could be sped up with a custom function).

**Comment by jeromekelleher** [comment]
> Does this make sense to you or would you prefer storing the child --> parent ordering?

Child->parent is nearly always better for representation when storing things because the number of parents any particular child has is bounded, whereas a parent can have any number of children. So, we can represent a diploid child->parent pedigree via a 2D array, but we'd have to have a ragged array if it was parent->child.

**Comment by jeromekelleher** [comment]
> My current implementation of topological sort (based on the Tskit implementation) is fast enough that I don't think that there's justification for storing the order. Instead we can just compute the order on the fly when needed. I'm currently getting around 2.9 ms for a random pedigree of 100,000 samples with 10 founders. 

Woot!

**Comment by timothymillar** [comment]
Done in #846
