### ISSUE TITLE
Allow kwargs in define_variable_if_absent

### ISSUE THREAD

**Issue by timothymillar** [pystatgen/sgkit#860]
I would like to allow the passing of keyword arguments to methods called with `define_variable_if_absent`. For example, the A-matrix (#859) is computed from the kinship matrix and requires some of the same arguments as the calculation of kinship matrix. If calculating the A-matrix automatically computes the kinship matrix without passing through those arguments then an incorrect A-matrix (and kinship matrix) may be returned.

I'm not sure if there has been previous discussion around when (not) to use  `define_variable_if_absent`? I can see that excessive use of it may lead to subtle errors so please comment if you think this a bad idea.

**Comment by tomwhite** [comment]
The change wouldn't change the rules in #352, would it? So I think it would be fine.

**Comment by timothymillar** [comment]
Ah, that's helpful thanks. In this case it would be similar to calling pbs(ds, estimator='nei') where the 'estimator' is passed through to Fst and also used directly in pbs. So I think it fits within those guidelines.

**Comment by timothymillar** [comment]
Done in #862
