### ISSUE TITLE
Disable numba caching via environment variable

### ISSUE THREAD

**Issue by timothymillar** [pystatgen/sgkit#869]
Edit: related to #371

I've recently started experimenting with sgkit on a [SLURM cluster](https://jobqueue.dask.org/en/latest/generated/dask_jobqueue.SLURMCluster.html) which is working well with the exception of methods using `guvectorize` with `cache=True`. Calling these functions results in a segmentation fault on the worker. This only seems to be an issue with `guvectorize` (not the `jit` or `vectorize` decorators) and there is no segmentation fault if I set `cache=False`.

There are a couple of open issues that may be related although neither quite match what I'm seeing (need to dig some more): 
- https://github.com/dask/distributed/issues/3450
- https://github.com/numba/numba/issues/4807

There is also an open issue for globally disabling numba caching which would provide a workaround although it might be stale:
- https://github.com/numba/numba/issues/4549

In the meantime, for the sake of debugging and workarounds, it'd be useful to be able to disable numba-caching in sgkit using an environment variable.

**Comment by tomwhite** [comment]
Can this be closed now that #870 is in?

**Comment by timothymillar** [comment]
Maybe we should leave it open for now to document the `SGKIT_DISABLE_NUMBA_CACHE` variable. I also wondered if you had a suggestion for testing that setting that variable works as expected in CI?

**Comment by benjeffery** [comment]
I've hit this via #1051. Interestingly I get a different error (`TypeError: can not serialize 'numpy.int64' object`) if I disable task fusion in dask (`dask.config.set({"optimization.fuse.active": False})`)
