### ISSUE TITLE
Wheels test on macOS on Python 3.10 fails

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#880]
There is no `cyvcf2` wheel for this combination, so we need to fix that. See https://github.com/brentp/cyvcf2/issues/245

Failure: https://github.com/pystatgen/sgkit/runs/7634527135?check_suite_focus=true

**Comment by tomwhite** [comment]
Superseded by #887

**Comment by hammer** [comment]
I think we need this or #887 to remain open until the upstream issue is fixed?
