### ISSUE TITLE
`test_max_str_len` failing due to change in upstream Dask

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#890]
See https://github.com/pystatgen/sgkit/runs/7831636851?check_suite_focus=true#step:5:1641

**Comment by tomwhite** [comment]
Using git bisect I found the problematic change in Dask: https://github.com/dask/dask/pull/9268

I haven't looked into it, so not sure what the best fix is yet.

**Comment by jeromekelleher** [comment]
The test itself is a bit complicated, and it looks like we're already special-casing the problematic empty array case. Maybe we should split it up into a three back-end specific tests, removing that parametrize? Hopefully that'll make it easier to follow/see what's going on.
