### ISSUE TITLE
Let vcf_to_zarr return the dataset

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit#909]
vcf_to_zarr current returns None, and it would be handy (for immediate inspection) if it returned the dataset instead. Looks like we're already loading the dataset, so it's no harm?

**Comment by tomwhite** [comment]
For performance reasons the dataset is no longer opened in `vcf_to_zarr` (since #933). So perhaps we should continue to return None, and users call `load_dataset` if they need to?

**Comment by jeromekelleher** [comment]
Ah - ok.
