### ISSUE TITLE
genotype_count_spec is inconsistent with VCF spec

### ISSUE THREAD

**Issue by timothymillar** [pystatgen/sgkit#911]
Just a minor inconsistency I noted given that we seem to follow the VCF spec in most cases. The `genotype_count_spec` states "the 3 columns contain heterozygous, homozygous reference, and homozygous alternate counts (in that order)". The VCF genotype ordering would typically be homozygous reference, heterozygous, homozygous alternate for a diploid biallelic variant as described for the "GL" field in the [spec](https://samtools.github.io/hts-specs/VCFv4.3.pdf).

**Comment by timothymillar** [comment]
Just to add to that, If we were to change the ordering to match VCF ordering then this variable could easily be generalized to multi-allelic variants and autopolyploids.

**Comment by tomwhite** [comment]
+1 to introducing a generalized ordering like GL.

It looks like the `genotype_count` variable is only used in `hardy_weinberg_test` - and it's optional. Does HWE generalize to multi-allelic/autopolyploids? If not, then we might leave HWE as it is, and rename its variable to `hwe_genotype_count_spec` or similar. If it does then we might want to consider changing it in HWE too, but may need to think about backwards compatibility (as it's optional it's possible it's not being used anywhere). I don't know why that order was used in HWE (@eric-czech might do).

**Comment by timothymillar** [comment]
> Does HWE generalize to multi-allelic/autopolyploids?

Yes in general although I'm not familiar with implementation details (something on my long term todo list).

**Comment by timothymillar** [comment]
@tomwhite I'm not sure how urgently you want to release 0.6.0 but I can try sort this tomorrow.

**Comment by tomwhite** [comment]
Thanks Tim, that would be great - I'll try to release next week.
