### ISSUE TITLE
Consider covariate orthogonalization for REGENIE

### ISSUE THREAD

**Issue by eric-czech** [pystatgen/sgkit#92]
This would remove covariates from the regression algebra, but this same step would still need to be run at the beginning of all stages.  It would still be an overall reduction in the complexity of the code though the performance impacts are less clear.

**Comment by hammer** [comment]
Linking to the Glow issue in case someone responds there https://github.com/projectglow/glow/issues/266

**Comment by eric-czech** [comment]
Leland's point in the issue that regularizing covariates is better anyhow is enough for me to think that the mild improvement in readability isn't worth the effort.  It does mean that our implementation and the one in Glow differ from the C++ implementation, but we could always parameterize the regularization as 0 for parity (though I'm sure there are several other differences).
