### ISSUE TITLE
Loading then saving a VCF imported dataset fails with `TypeError: expected unicode string, found 130`

### ISSUE THREAD

**Issue by benjeffery** [pystatgen/sgkit#991]
```python
vcf_to_zarr("example.vcf.gz", "vcf.zarr")
ds = sg.load_dataset("vcf.zarr")
sg.save_dataset(ds, "vcf2.zarr")
```
Currently fails with 
`TypeError: expected unicode string, found 130`
I believe this is due to https://github.com/pydata/xarray/issues/3476 as the workaround suggested there:
```python
    for v in list(ds.coords.keys()):
        if ds.coords[v].dtype == object:
            ds[v].encoding.clear()

    for v in list(ds.variables.keys()):
        if ds[v].dtype == object:
            ds[v].encoding.clear()
```
prevents this error. I'm not sure there is anything sgkit can do about this - looking into it.

**Comment by tomwhite** [comment]
See also #852

**Comment by benjeffery** [comment]
Ahh, nice! Didn't see that, thanks @tomwhite.

**Comment by benjeffery** [comment]
I can confirm that using sgkit `HEAD` fixes this issue.
