### ISSUE TITLE
Generic approach to converting between kinship and relationship estimates

### ISSUE THREAD

**Issue by timothymillar** [pystatgen/sgkit#994]
The kinship and (additive) relationship matrices are closely related. This is simply `kinship * ploidy = additive_relationship` for samples of a single ploidy (a bit more complicated in mixed ploidy datasets). In sgkit there are multiple methods for estimating kinship or relationship matrices, but no standard way to convert between them.

Kinship estimators:
- `pedigree_kinship`
- `pca_relate`
- `Weir-Goudet_beta`

Relationship estimators:
- `genomic_relationship`

We also have a method `pedigree_relationship` which converts a kinship matrix to a relationship matrix. This is actually a generic conversion, but it targets the pedigree specific variables within the spec. In retrospect, I think that the `pedigree_relationship` method (in its current form) may have been a mistake as it implies that there should be separate conversion methods for each case. 

We could instead:

- Have generic `kinship_as_relationship` and `relationship_as_kinship` methods. Annoyingly these would have to return generic `stat_relationship` and `stat_kinship` variables.
- Leave it to the user to perform these simple conversions (with suitable documentation).

With regard to the `pedigree_kinship` and `pedigree_relationship` methods, I think it'd be better to combine them into a single method  which (optionally?) returns both the relationship and kinship matrices. My guess is that the relationship matrix will be used more commonly, but the kinship matrix is calculated as an intermediate and we want to avoid kinship -> relationship -> kinship. 
It's a bit awkward calling `pedigree_kinship` and then `pedigree_relationship` in their current state with non-diploid datasets (converting tau to ploidy).

Thoughts?

**Comment by jeromekelleher** [comment]
This sounds good @timothymillar - have you suggestions for an API?

**Comment by jeromekelleher** [comment]
Just to confirm, these are updates to currently unreleased APIs, so good to do this before release?

**Comment by timothymillar** [comment]
Yes, the entire `pedigree.py` submodule is new since `0.5.0`.

> suggestions for an API?

Given that I've flip-flopped on the `pedigree_relationship` API quite a bit, I think we want a simple approach (and to avoid holding up `0.6.0`). I also think we need to be careful about placing too much burden on users to track dependencies between variables. 

I suggest we remove the `pedigree_relationship` method and add a `return_relationships=False` argument to `pedigree_kinship`. If `return_relationships=True`, then the additive relationship matrix is returned in *addition* to the kinship matrix. This should strike a balance between convenience (many will just want the relationship matrix) and ensuring that the kinship method/matrix is correctly mapped to the additive relationship matrix.

Probably best to avoid adding generic conversions to the public API for now.

**Comment by tomwhite** [comment]
> If `return_relationships=True`, then the additive relationship matrix is returned in _addition_ to the kinship matrix.

These are just variables in the returned dataset, right? If so, sounds good to me.
